### ISSUE TITLE
Per-book advancement locking

### ISSUE THREAD

**Issue by noobanidus** [Vazkii/Patchouli#102]
Currently as it stands it is only possible to prevent advancement locking for all Patchouli books in a mod pack. This means using Universal Bestiary as an unlocked book also requires, for example, that you also use the Twilight Forest book unlocked.

I imagine this could be achieved with a per-book configuration option within Patchouli's config file instead of a global flag.

**Comment by Wabbit0101** [comment]
It would also be nice to be able to signal in book.json that a book isn't related to advancements at all (to get rid of the UI bar altogether for that book).
