### ISSUE TITLE
Ticking Memory Connection

### ISSUE THREAD

**Issue by O13SC3N3** [Vazkii/Patchouli#106]
1.12.2 Minecraft Forge 2768

https://paste.dimdev.org/igukayujax.mccrash

Not sure whats going on back tracking to see if another mod is Involved but the error is stating Patchouli and FastWorkBench. On World Creation and Modpack load everything is fine, everything loads smooth and the console reports errors with Advancements which seems to be the norm. However once save and quitting which is also fine, when you got to reopen the world It throws this error and will not reload. You can create a world just fine and play, until you save and exit and want to play again.

Posted at both.

**Comment by Ellpeck** [comment]
You have a mod installed that adds a null advancement to the registry (for some reason).
This has already been fixed in #105 and will be rolled out with the next release.

It'd be cool if you'd try to find the mod that actually causes this, though.

**Comment by O13SC3N3** [comment]
Ill try it wasn't that long ago actually. Im at the point where if it was possible to have a mod that just hijacks and removes all advancements all together to prevent these issues. But ill repost once I find which one.

**Comment by O13SC3N3** [comment]
Natural Auras is the culprit in my modpack
