### ISSUE TITLE
Suggestion all in game GUI

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Vazkii/Patchouli#107]
Alright so I suck. I cannot get this to work despite how hard I try. Can you create an all ingame GUI creator? This is a great mod idea and even better for rpg based servers but making a book for none coders like myself seems to be too hard.

**Comment by Ellpeck** [comment]
No, that's not planned, sorry.

**Comment by Drullkus** [comment]
What is it that you’re trying to do? What’s the problem you’re trying to solve?

**Comment by P3rf3ctXZer0** [comment]
I just suck at using this mod. It is not noob friendly. FTB shop is noob friendly.
