### ISSUE TITLE
quark, autoreglib and patchouli

### ISSUE THREAD

**Issue by Yoghurt4C** [Vazkii/Patchouli#108]
when using `quark:limestone` or  `quark:limestone[type=stone_limestone]` as part of a patchouli multiblock, the game crashes upon anchoring its visualization
https://pastebin.com/pabqYreE

**Comment by Ellpeck** [comment]
Please provide the multiblock code.
Also, it looks like the property is `STONE_LIMESTONE `and not `stone_limestone`, but I'm not sure if that's the issue here.

**Comment by Yoghurt4C** [comment]
```"multiblock": {
				"mapping":{
					"0":"quark:limestone",
					"L":"quark:limestone"
				},
				"pattern":[
					["____________",
					"____________",
					"____LLLL____",
					"___LLLLLL___",
					"__LL____LL__",
					"__LL____LL__",
					"__LL____LL__",
					"__LL____LL__",
					"___LLLLLL___",
					"____LLLL____",
					"____________",
					"____________"
					]
```
doubt this is helpful information because it seems it's not an issue inherently on the side of patchouli 😹
