### ISSUE TITLE
issues adding images

### ISSUE THREAD

**Issue by bennyb1971** [Vazkii/Patchouli#109]
Cant seem to figure out how to add an image page. Do i need to put the images in a certain directory?

**Comment by Vazkii** [comment]
You need to get a mod like Resource Loader and put the images in the
resources directory.

**Comment by bennyb1971** [comment]
ok i added Resource loader. Placed the image in the resources folder (see 1st image). Added an image page to my book (image canvas size is 200x200px). I still get the purple and black squares as image (see 2nd image). I will also upload the page file for my page (see 3rd image)
![error](https://user-images.githubusercontent.com/15984199/53253134-d368eb00-36c0-11e9-8fbf-e3e894457352.PNG)



![folder](https://user-images.githubusercontent.com/15984199/53252871-34dc8a00-36c0-11e9-814a-250ffd179df5.PNG)
![error](https://user-images.githubusercontent.com/15984199/53252998-82f18d80-36c0-11e9-9289-a746562aa35a.PNG)

**Comment by bennyb1971** [comment]
apparently the image with my code wasnt attached, so i will attach it now
![code](https://user-images.githubusercontent.com/15984199/53253194-fb584e80-36c0-11e9-8da5-01a4010e72bc.PNG)

**Comment by bennyb1971** [comment]
after fiddeling with it for a bit it suddenly works. Issue closed

**Comment by BranTuna** [comment]
I'm having the same problem. I entered "resources:folder/image.png" format and it never seems to work. Can you define "Fiddling with it a bit"?

**Comment by sigmasoldi3r** [comment]
> I'm having the same problem. I entered "resources:folder/image.png" format and it never seems to work. Can you define "Fiddling with it a bit"?

Yeah, I could use some help also... :/ I hate issues closed with an "ah, somehow I fixed it" 😭

**Comment by Codiak540** [comment]
@BraniyaKz @sigmasoldi3r I'd assume they changed `"images"` from `"go2.png"` to the full resourceLocation of the png, for instance, `"minecraft:go2"`

**Comment by Jmynii** [comment]
ive been trying to figure out how to get the image using open loader but im not sure how
