### ISSUE TITLE
Unable to load custom book

### ISSUE THREAD

**Issue by baka-gourd** [Vazkii/Patchouli#115]
### May be the system cause:D
Unable to load custom book.
System:ubuntu18.04
Default language:Chinese
![2019-03-12 22-47-27 的屏幕截图](https://user-images.githubusercontent.com/36119339/54210223-0f51dc00-451a-11e9-8937-1069f9729dab.png)
![2019-03-12 22-47-48 的屏幕截图](https://user-images.githubusercontent.com/36119339/54210239-17118080-451a-11e9-9f87-c61951fcff2e.png)

**Comment by Ellpeck** [comment]
Try using no spaces in the book's folder name as well as ASCII characters for the file names only.
