### ISSUE TITLE
Preinitializing NullPointerExceptions

### ISSUE THREAD

**Issue by KNBrisson** [Vazkii/Patchouli#118]
When the game begins pre-initialization, it will crash as soon as it reaches Patchouli. This is due to Patchouli throwing a NullPointerException, as showcased in this hastebin: https://hastebin.com/usunodipeq.rb

Patchouli is version 1.0-16
 forge-1.12.2-14.23.5.2811

**Comment by thePalindrome** [comment]
I had a similar issue, caused by me not specifying "version" in book.json, I manually set it to "0" (which *should* be the default according to the docs).
