### ISSUE TITLE
Multiple non-functional empty bookmarks appear on books

### ISSUE THREAD

**Issue by zabi94** [Vazkii/Patchouli#125]
- Issue exists from version 1.0-12 through 1.0-18 at least, I haven't tested any further.
- Forge 14.23.5.2815
- Windows 10
- Eclipse dev-env.
- Single Player

The mod I'm working on adds 3 separate books, in two of them one or more empty bookmarks appear on the right. Clicking on them adds a new bookmark if I'm reading an entry (but won't remove it if holding shift), but won't do anything when I'm exploring the content index and chapters page, and they can't be removed. Clicking multiple time while reading an entry causes a new bookmark to show up to that page for every time I click on it.
Other bookmarks seem to work just fine, they can be removed and they link to the correct page.
The tooltip says "Add bookmark" when hovering on them

The issue persists through different worlds and client restarts.
![Screenshot](https://user-images.githubusercontent.com/11521878/55827607-ddc53400-5b0a-11e9-9dd2-5930992129f0.png)
This book, the third added (resource name "rituals"), has several of them.
The second book added (resource name "brewing") only has one.
The first book added (resource name "witchcraft") has none.

**Comment by Insane96** [comment]
Happens to me too when entries are removed / renamed

**Comment by zabi94** [comment]
Yup. I already submitted a PR to fix this
