### ISSUE TITLE
Crash with AoA

### ISSUE THREAD

**Issue by Rongmario** [Vazkii/Patchouli#128]
Crash: https://paste.dimdev.org/anomugegor.mccrash

https://github.com/Tslat/Advent-Of-Ascension/issues/593

**Comment by Rongmario** [comment]
Possibly linked to https://github.com/Vazkii/Patchouli/issues/124

**Comment by Vazkii** [comment]
Patchouli doesn't remove anything, so this should be on FastWorkbench.
