### ISSUE TITLE
Pencile (update) button disappeared

### ISSUE THREAD

**Issue by Cakestory** [Vazkii/Patchouli#137]
Hi,
using version "1-0-20" of patchouli, the pencil button for updating book content while ingame suddenly disappeared and cannot be brought back.
I am creating a guide book for my modpack from json files in the patchouli_books folder following the instructions on your wiki, but at some point (could have been after restarting the game for the first time, but can´t say it for sure) the pencil button in my books was gone.
I tried deleting patchouli´s config, patchouli_data.json and even deleted my book and replaced it with the basic one from this wiki page:
[https://github.com/Vazkii/Patchouli/wiki/Getting-Started](url)

The button is still missing.
The log file prints no messages about patchouli except for the common "[FML] Mod patchouli is missing the required element 'version'..." warning.

**Comment by Ellpeck** [comment]
You need to be in creative mode.

**Comment by Cakestory** [comment]
Omg. Thanks. That solved the problem. :D
