### ISSUE TITLE
Crash with JAR Launcher.

### ISSUE THREAD

**Issue by Danymaddox** [Vazkii/Patchouli#139]
Well, I'm using the old JAR launcher because the native one its just not working for me. The case is that I'm getting this crash with Patchouli every time forge tries to load it. I've tried with just forge and Patchouli. Here you have the crashlog and more info:

Crashlog: https://pastebin.com/CAj3i1nZ
Forge: 14.23.5.2838
Launcher: JAR Launcher AND Twitch app.
OS: Windows 10.

**Comment by netish** [comment]
This is a random suggestion - but sometimes I've seen the nullpointer exception you have if you have an outdated version of forge. If you are running 1.12.2 that is the right version of patchouli, but try updating to forge 14.23.5.2847. If you are running 1.14.2 you need the 1.1-24.jar. and to update forge as well.
