### ISSUE TITLE
[bug] Some recipes are not rendered.

### ISSUE THREAD

**Issue by lublak** [Vazkii/Patchouli#148]
I misunderstood something.
It does not need the id of the recipe result, but the recipe id itself.

--------------------------------------------------------------------

~~I look if i found more information about it.
Okay it about "tconstruct:book" and some other items that are impossible to render.~~

~~This Entry works fine:~~
```json
{
    "name": "Armory Addendum",
    "icon": "conarm:book",
    "category": "books",
    "pages": [
      {
        "type": "text",
        "text": "Do you want make your own armory combinate made of different materials?$(br)This book is for you."
      }, {
		"type": "crafting",
		"title": " ",
		"recipe": "conarm:book"
	  }
    ]
}
```
![grafik](https://user-images.githubusercontent.com/44057030/65191008-ee42e880-da72-11e9-9359-b71b3009265b.png)

~~but this is emty:~~
```json
{
    "name": "Materials and You",
    "icon": "tconstruct:book",
    "category": "books",
    "pages": [
      {
        "type": "text",
        "text": "Do you want make your own tools combinate made of different materials?$(br)This book is for you."
      }, {
		"type": "crafting",
		"title": " ",
		"recipe": "tconstruct:book"
	  }
    ]
}
```
![grafik](https://user-images.githubusercontent.com/44057030/65191100-3b26bf00-da73-11e9-9b04-f3f52233c3c3.png)

**Comment by BranTuna** [comment]
Thank you for figuring this out, because I had a swell time trying to figure out why my recipes weren't rendering, also. :P
