### ISSUE TITLE
5th subcategory overlapping 

### ISSUE THREAD

**Issue by thanasishadow** [Vazkii/Patchouli#150]
Minecraft: 1.12.2
Forge: 14.23.5.2847
Patchouli: 1.0-20

I have a category with 5 subcategories. One of those subcategories overlaps with whichever other subcategories has the 1st spot. Changing the sortnum doesn't affect this. The 1st subcategory place displays the icon of the overlapping subcategory but hovering over it gives the name of the 5th one. Also, clicking on that spot, opens the 5th subcategory and upon right clicking (to exit), shows the overlapping subcategory.

Main Category (0fromashes.json):
`{
	"name": "From Ashes Wands",
	"description": "Information about the wands added by this modpack",
	"icon": "contenttweaker:mawhemenus_wand",
	"sortnum": 0
}`

5th Subcategory (mawhemenuswand.json):
`{
	"name": "Mawhemenus Wand",
	"parent": "0fromashes",
	"description": "wip",
	"icon": "contenttweaker:mawhemenus_wand",
	"sortnum": 0
}`

Overlapping Subcategory (firewand.json):
`{
	"name": "Fire Wand",
	"parent": "0fromashes",
	"description": "wip",
	"icon": "contenttweaker:fire_wand",
	"sortnum": 1
}`

**Comment by thiakil** [comment]
I'm seeing this too. (1.15.2-1.2-34.178)

![image](https://user-images.githubusercontent.com/1788847/82301558-021c6100-99eb-11ea-8dd6-b9eb56f7289a.png)

![image](https://user-images.githubusercontent.com/1788847/82301631-16f8f480-99eb-11ea-9614-8ac8d15d5591.png)

On hover it will show the 2nd icon, but click will take you to the first subcategory
