### ISSUE TITLE
NPE while drawing screen after crafting

### ISSUE THREAD

**Issue by ticviking** [Vazkii/Patchouli#154]
I've been tracking down behavior I first observed [here](https://github.com/codetaylor/pyrotech/issues/12) where sometimes crafting an item would trigger crash. 

The crash happens sometimes when crafting items that trigger either a new recipe or an advancement. This [crash log](https://gist.github.com/ticviking/08b1fe570c1c9f6360cc6914fd7d8614) narrows down the culprits to either in Patchouli or Forge. (I have reproduced it in both twitch and multimc.

I'm new enough to modding(and Java) that I'm struggling to get a debugger attached to an instance with decompiled source to actually track down what is causing the problem in more detail myself. 

This looks like it may be related to #135 so I'll be trying some of the mentioned workarounds there to narrow things down.

**Comment by Vatruvius** [comment]
I can confirm I am experiencing this issue as well. Moved over from linked forum issue above.
