### ISSUE TITLE
[Feature Request] Add Item To Book To Unlock Entry

### ISSUE THREAD

**Issue by LunariusH** [Vazkii/Patchouli#159]
I would love to have entries be able to be unlocked by placing an item in a page of the book.  For example:

I use Serene Seasons and Pam's Harvestcraft. I'd like to have the growing season, preferred biome, and growth time (in Minecraft Days) appear in the book when the end-user places a seed in the book.  This would unlock information about that seed.

I can think of countless other uses for this feature, but this is the one that comes immediately to mind.

**Comment by williewillus** [comment]
is there are a reason you can't use an advancement that detects the item and have the entries be gated on that advancement? seems 90% the same to me besides the part where you have to drag the item in instead of it unlocking once you pick it up
