### ISSUE TITLE
Thaumcraft Issue w/ Visualizing 

### ISSUE THREAD

**Issue by sleepyKitsune** [Vazkii/Patchouli#16]
![2018-11-11_13 26 53](https://user-images.githubusercontent.com/37781809/48316868-13470f00-e5b7-11e8-8422-a25e72c27e12.png)
I had this issue when trying to visualize the tree altar.

Mods Installed:

Baubles
JEI
Nature's Aura
Patchouli
Thaumcraft
FORGE: 14.23.5.2772

**Comment by Vazkii** [comment]
Let me know if the next update solves this. It probably won't but just in case

**Comment by sleepyKitsune** [comment]
Ok, In the afternoon tomarrow I will try it.

**Comment by Hubry** [comment]
Confirmed this is working with latest Patchouli.
![obraz](https://user-images.githubusercontent.com/26120076/48493419-1139b600-e82c-11e8-8528-8f7f9d3b34b9.png)
