### ISSUE TITLE
Making Links trigger Minecraft commands

### ISSUE THREAD

**Issue by defilerzero** [Vazkii/Patchouli#163]
Was wondering what possibility there is to include the functionality of a link in the book triggering a console command. Example, teleporting to a location, give player X item, or setting a gamemode, etc.

**Comment by williewillus** [comment]
Done, clicking the link will send the parameter as a command to the server.


With this you can do the same things vanilla books do to execute privileged stuff from an unprivileged player (you use /trigger and scoreboard objectives and have something else like an mcfunction or command block reacting to the scoreboard objectives)
