### ISSUE TITLE
Can't nest formatting strings

### ISSUE THREAD

**Issue by Alwinfy** [Vazkii/Patchouli#167]
Currently on Patchouli 1.1-22, Forge 28.1.102 for 1.14.4.
Attempting to put formatting inside a tooltip, e.g. `$(t:$(o)foo)bar`, yields `foo)bar` with `$(o` when hovered, as opposed to `bar` with *`foo`* when hovered.

**Comment by netish** [comment]
Might I suggest doing `$(o)$(t:foo)$()bar` instead? This will add the italics, then tooltip, then end formatting, and display bar without tooltip or italics. There is nothing in the wiki that suggests tooltips can be nested, only lists $(li maybe.
