### ISSUE TITLE
Resizing GUI makes all GUIs not appear

### ISSUE THREAD

**Issue by Partonetrain** [Vazkii/Patchouli#169]
If I change the GUI size, all GUIs disappears entirely. I can press ESC afterwords to get out of the book, but opening any other GUI after that will lock up the game. I have to manually modify patchouli_data.json to fix my client.

Forge 28.1.102
Patchouli 1.1-2.2
Other mods
Log (doesn't seem to show the error, though, just locks up at "can't keep up"): https://pastebin.com/kHp1sEqm

**Comment by williewillus** [comment]
can you try with just patchouli?

**Comment by Partonetrain** [comment]
Tested with just Patchouli. After opening a book and pressing the resise button:
![image](https://user-images.githubusercontent.com/19861808/70675286-63772180-1c4e-11ea-8f6a-9033a93f3777.png)

Same thing happens, except opening other GUIs doesn't lock up the game, they just don't show up at all after opening a resized Patchouli GUI. For example, opening a chest:
![image](https://user-images.githubusercontent.com/19861808/70675415-c23c9b00-1c4e-11ea-8417-a48578244a17.png)

**Comment by williewillus** [comment]
thanks, will look into it

**Comment by williewillus** [comment]
fixed in 23+
