### ISSUE TITLE
Resizing book GUI cause recipe tooltips to be misplaced

### ISSUE THREAD

**Issue by Terpo** [Vazkii/Patchouli#174]
I am working for a manual for my 1.14 forge mod.

The dependency for patchouli is: 1.1-23.111

Using the large UI size in patchouli moves the tooltips of the recipe pages.

![grafik](https://user-images.githubusercontent.com/4256058/71289324-307b0f00-236d-11ea-9838-f49a4978a2c3.png)

The cross marks the mouse pointer. If the book uses the default size everything is fine.

**Comment by williewillus** [comment]
does the new version of patchouli (24) exhibit this issue?

**Comment by Terpo** [comment]
Nope, still broken.
