### ISSUE TITLE
Crashes the game while loading

### ISSUE THREAD

**Issue by ghost** [Vazkii/Patchouli#175]
Crash report thingie
https://pastebin.com/5Cetq92u   <-- no idea what happend but it starts at line 420 for 
                                                            some reason

Image
![Sieppaa](https://user-images.githubusercontent.com/59287192/71545784-b3b4ea00-2997-11ea-94df-87ff224afa03.PNG)

**Comment by Alexaario** [comment]
Might be a problem at my end but if you know what causes this please leave a comment.

**Comment by JustCuz0** [comment]
I have the same problem when trying to run MCEternal
The linked report: https://paste.dimdev.org/idivitizol.mccrash

Would appreciate if someone knew how to fix
