### ISSUE TITLE
Can't find my book in 1.14.4 version

### ISSUE THREAD

**Issue by congueror** [Vazkii/Patchouli#176]
Am not sure if am doing something wrong or if it's the mod's problem but my book will not appear in-game. Am using Patchouli v 1.1-24 MC v 1.14.4 and after following the wiki and launching my game, I use the /give command but my the only thing that shows up under patchouli: is patchouli:guide_book , which is just an item(no special functions). Here's my path if it helps:

- patchouli_books
   - quest_book(folder, my book's name)
      - en_us(folder)
         - categories
         - entries
         - templates
      - book.json(JSON File)

Here are the contents of the json file:

{
	"name": "Quest Book #1",
	"landing_text": "This is the",
	"version": 1
}

**Comment by williewillus** [comment]
you need to specify your book in the nbt tags. Here is something that should work:
`/give @p patchouli:guide_book{'patchouli:book': 'yourdomain:quest_book'}`

where `yourdomain` is either your modID (if you're a modder), or the subdirectory of `/data/` your patchouli_books folder is located in.
