### ISSUE TITLE
Crash from Rendering Screen

### ISSUE THREAD

**Issue by BranTuna** [Vazkii/Patchouli#177]
### Issue Description
In several cases, the game tends to freeze and crash at random times whilst reading patchouli books.
Also, my custom book isn't loading in its images or crafting recipes, despite following direction and having no errors. ??? Idk.

### Crash Report
[https://pastebin.com/1GynERP2](url)

**Comment by netish** [comment]
#184 Mine is similar and gives same error.

**Comment by BranTuna** [comment]
I'm not even sure if it's from this mod, or even a memory issue.
