### ISSUE TITLE
Rendering Overlay Crash

### ISSUE THREAD

**Issue by WenXin20** [Vazkii/Patchouli#179]
`Minecraft v1.14.4`
`Forge v28.1.109`
`ElecCore v2.0.25-beta`
`Crafting Table IV v1.6.119`
`Hwyla v1.10.6-B67`
`Glacia v14.4.1b`
`Patchouli v1.1-24`

I got this crash with these 5 mods, but if Glacia or Crafting Table IV is removed, the crash does not happen. ElecCore & Hwyla is required for Crafting Table IV to work.
The mods Glacia & Crafting Table IV also crash together, but when Patchouli is added, it crashes instead. So it might be that Patchouli wasn't closing properly, which can make it hard to figure out the source of the crash.
[Crash Report](https://gist.github.com/WenXin20/eba16da78ad70a335eb711b70c3352e1)

**Comment by WenXin20** [comment]
I got this crash again, but this time with only Traverse v2.0.3 & Patchouli. I believe this is because Patchouli crashes instead of displaying the error screen that would normally display what went wrong. Normally, a screen would come up saying that Traverse is missing the Mystical Lib mod, but Patchouli crashes instead.

**Comment by frakier** [comment]
Had this error and came here to check, saw this issue. Checked and I needed to update mysticallib-1.14.4-1.13.0.jar, updated and it worked.

**Comment by WenXin20** [comment]
Yeah, that's because Patchouli is crashing instead of displaying the forge screen that Mystical Lib is outdated/missing.

**Comment by CvoidWyvern** [comment]
Found that this crash can also override the "x mod requires [forge version]", at least on the newest version of Patchouli. Seems to just be anything that would bring up that screen.
