### ISSUE TITLE
Game crashes while loading

### ISSUE THREAD

**Issue by gamer569** [Vazkii/Patchouli#183]
Might just be a problem on my end but I'm reporting it anyway. Report:
https://paste.dimdev.org/adipumanuc.mccrash

**Comment by netish** [comment]
Unterminated object at line 4 column 3 path $.landing_text - check your main book json there is an ending symbol missing in line 4

**Comment by gamer569** [comment]
I added the ending symbol and it still crashed.

**Comment by netish** [comment]
New pastebin log? You might have more errors - it will just crash and list the first one it encounters.

**Comment by gamer569** [comment]
https://paste.dimdev.org/suzocezare.mccrash

**Comment by netish** [comment]
Unterminated object at line 4 column 2 path $.landing_text - you have another unclosed bracket - might I suggest linking me your book - I'll look at it for you?

**Comment by gamer569** [comment]
[book_lol.zip](https://github.com/Vazkii/Patchouli/files/4065704/book_lol.zip)

**Comment by netish** [comment]
You need a comma after the landing text ends - .",
