### ISSUE TITLE
Render Overlay Crash Patchouli

### ISSUE THREAD

**Issue by StarboardHook** [Vazkii/Patchouli#185]
Idk the exact reason for the crash but here is the crash report.
its the 1.14.4 version. guessing from report id say its something to do with the patchouliItem.class

https://paste.dimdev.org/guzorowomo.rb

**Comment by Seikikai** [comment]
Same Issue

https://paste.link/p2/v6USz8kU0CsaWtwj-HRV9w.txt

**Comment by williewillus** [comment]
Can the full debug.log be posted?

**Comment by Seikikai** [comment]
Atm Using The Recently Updated 1.1-25 For 1.14 So Seems The Error Been Fixed

**Comment by frakier** [comment]
Patchouli-1.14.4-1.1-26.jar
intermittent crash on forge 28.2.0 but I have a lot of mods as well that could be contributors to the problem.
RandomPatches is mentioned in some of the error reporting.

logs have been sanitized of user info as best I can
[debug.log](https://github.com/Vazkii/Patchouli/files/4332260/debug.log)
[crash-2020-03-13_23.30.13-client.txt](https://github.com/Vazkii/Patchouli/files/4332262/crash-2020-03-13_23.30.13-client.txt)

**Comment by CSchlaud04** [comment]
I have also been having this crash using Patchouli-1.14.4-1.1-26, Forge version 28.2.3. The only mods I have loaded are Botania+r1.11-378, Curios-FORGE-1.14.4-1.0.2, and an in-dev mod I am currently working on.
[crash-2020-03-14_12.41.37-client.txt](https://github.com/Vazkii/Patchouli/files/4333123/crash-2020-03-14_12.41.37-client.txt)
