### ISSUE TITLE
Digsite Modpack Crashes while loading 

### ISSUE THREAD

**Issue by ArrZeroZeroTwoSeven** [Vazkii/Patchouli#187]
According to the crash screen i guess patchouli is the issue i dont know anything about this kind of stuff but heres the crash log https://paste.dimdev.org/raw/bozuhanefo

**Comment by ArrZeroZeroTwoSeven** [comment]
after looking some more into the issue on google it looks like its caused by having it set to jar launcher rather than native launcher which is an issue since the pack wont even start to launch when i have it on native so i guess i have to avoid patchouli when playing modded

**Comment by ArrZeroZeroTwoSeven** [comment]
[latest.log](https://github.com/Vazkii/Patchouli/files/4112743/latest.log)

**Comment by ArrZeroZeroTwoSeven** [comment]
https://pastebin.com/jPFcY2zr    latest.log file

**Comment by ArrZeroZeroTwoSeven** [comment]
i have just atempted to make a mod pack with nothing but patchouli in it and got similar error

**Comment by wideblaze** [comment]
user installed ONLY Minecraft 1.12 + Patchouli mod via twitch and still crashed

https://pastebin.com/sR508WKu

user was able to load without crashing using MultiMC instead of twitch

I believe this issue can be closed
