### ISSUE TITLE
Dependency string in readme is incorrect

### ISSUE THREAD

**Issue by Daomephsta** [Vazkii/Patchouli#19]
The first colon should be a period, the correct dep string is `compile "vazkii.patchouli:Patchouli:[VERSION]"`

**Comment by 0999312** [comment]
Don't forget to replace [VERSION] with the version of the mod that you want to work with!
The original words from README.(; = =)

**Comment by Daomephsta** [comment]
Please read what I said. The issue has nothing to do with the version. It's the group that's wrong.

**Comment by Daomephsta** [comment]
Fixed by #10
