### ISSUE TITLE
Invalid JSON Crashes Instead of Just Throwing an Error

### ISSUE THREAD

**Issue by InQuognito** [Vazkii/Patchouli#190]
Minecraft 1.14.4
Forge 28.1.116

`[29Jan2020 15:57:09.441] [modloading-worker-1/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: com.google.gson.stream.MalformedJsonException: Unterminated object at line 6 column 3 path $.version
    Index: 1
    Listeners:
        0: NORMAL
        1: net.minecraftforge.eventbus.EventBus$$Lambda$1994/1181708889@2fbb2af6
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 6 column 3 path $.version
    at com.google.gson.Gson.fromJson(Gson.java:902)
    at com.google.gson.Gson.fromJson(Gson.java:825)
    at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:98)`

^^ A block from my crash log, crashed repeatedly. Ran my book.json through a JSONLint to find out that I was missing a comma. I think the program is supposed to throw an error and just not load the book.

**Comment by williewillus** [comment]
I'll fold this into #191
