### ISSUE TITLE
[Fabric] Advancement triggers/completions seem to not function.

### ISSUE THREAD

**Issue by martmists** [Vazkii/Patchouli#193]

**Comment by williewillus** [comment]
can you upload a test datapack+book?

**Comment by martmists** [comment]
[AOF-Expert](https://github.com/AllOfFabric/AOF-Expert) is what we use for testing right now.

**Comment by williewillus** [comment]
cannot reproduce

**Comment by williewillus** [comment]
make sure
1. you're declaring the advancement namespace in the book json
2. said namespace is not minecraft, there's a legacy technical thing where vanilla advancements cannot be used to gate (It's a pretty arbitrary restriction so I'm looking into dropping it, but still)
