### ISSUE TITLE
[Wiki] Wiki link for "Book Examples" on home page is broken (points to assets/ instead of data/)

### ISSUE THREAD

**Issue by ThePuzzlemaker** [Vazkii/Patchouli#194]
The wiki link for "Book Examples" on home page is broken (points to the master branch's [assets/](https://github.com/Vazkii/Patchouli/tree/master/src/main/resources/assets/patchouli/patchouli_books) instead of [data/](https://github.com/Vazkii/Patchouli/tree/master/src/main/resources/data/patchouli/patchouli_books))

**Comment by williewillus** [comment]
Fixed
