### ISSUE TITLE
[Issue][Recipe-Page]: Mismatched tool-tip hovering areas in medium-large and large gui-scales.

### ISSUE THREAD

**Issue by Lanse505** [Vazkii/Patchouli#200]
When using the journal in medium-large and large mode, the hovering area for text for items in the crafting area are mismatched compared to where they should be, see the pictures below:

Medium-Large:
![bild](https://user-images.githubusercontent.com/1495068/76131945-c0496480-6010-11ea-876f-c550f76b66c5.png)

Large:
![bild](https://user-images.githubusercontent.com/1495068/76131959-ce978080-6010-11ea-8d60-1a7db826b9d6.png)

**Comment by Lanse505** [comment]
Accidentally pressed enter, will fill this in sec.

**Comment by williewillus** [comment]
see #174 (also help wanted, not sure where the exact issue is here)
