### ISSUE TITLE
[1.15.2] Linkage error after updating to 1.15.2-1.2-29.148/9

### ISSUE THREAD

**Issue by klikli-dev** [Vazkii/Patchouli#202]
# Description
After updating from 1.15.2-1.2-29.147 to 1.15.2-1.2-29.149 (and thus also switching the dependencies to use :api with compileOnly), I get the following crash: https://gist.github.com/klikli-dev/56afa773f1c41d37b12049886049584c when calling PatchouliAPI.instance.looseBlockMatcher

When downgrading back to 147 and unified jar this works.
The issue can be reproduced with https://github.com/klikli-dev/occultism/commit/dc01b60eeebeabb16a1e6f97ea1968d59828d7a8 (the next commit reverts the version update).

**Comment by williewillus** [comment]
when are you calling this method?

**Comment by klikli-dev** [comment]
To get a loosen block matcher for a multiblock. 

I'm currently building against the full jar though because I have a custom book item (which needs access beyond the api as far as I can tell), then this error naturally does not appear.

**Comment by williewillus** [comment]
> To get a loosen block matcher for a multiblock.
no, like, during what part of the loading cycle

This log is because you're calling this method **really** early, and the classloader does not like that since it's causing circular loading of the same class.

Call it later (during SetupEvent), don't use a static initializer or something

**Comment by daniel-eder** [comment]
> This log is because you're calling this method **really** early, and the classloader does not like that since it's causing circular loading of the same class.
> 
> Call it later (during SetupEvent), don't use a static initializer or something
Sorry, was a bit sleep deprived when reading this.
This log is called during a registry event, but the same happens when calling in commonsetup. 
If I'm the only one feel free to close it, as mentioned above its currently not reproducing because I build against one jar only.

**Comment by klikli-dev** [comment]
Sorry, I was a bit sleep-deprived when reading your first question.
The log posted above comes from when calling it during a registry event, however the same error appears also when running it in the common setup event. 

If I am the only affected person feel free to close it, as I am currently building against the full jar due to my custom book.
