### ISSUE TITLE
[1.15.2] Links do not work

### ISSUE THREAD

**Issue by Boomflex** [Vazkii/Patchouli#205]
Hello,

Using Patchouli-1.15.2-1.2-28 and when you create a link it doesn't actually become clickable.

![image](https://user-images.githubusercontent.com/22868795/76807263-b7f4e480-67db-11ea-872a-adc5293bc3a1.png)

As you can see from the image, it recognises it as a link but doesn't click through.

Also the link in the Editor (pic below) doesn't click through either.

![image](https://user-images.githubusercontent.com/22868795/76807304-d22ec280-67db-11ea-8da3-2cadbbd51596.png)

**Comment by Boomflex** [comment]
Further to this I have just noticed that the external links are showing a lot lower, note the cursor placement.

https://i.imgur.com/au9rcMX.png

https://i.imgur.com/VGymxxb.png

**Comment by williewillus** [comment]
they do work (they do in Botania 1.15), I think you're just running into #174, so I'm gonna fold this into that issue
