### ISSUE TITLE
[1.15.2]The load screen repeats indefinitely

### ISSUE THREAD

**Issue by EnterFor** [Vazkii/Patchouli#210]
Forge：31.1.30
Mod：Patchouli-1.15.2-1.2-28.jar

The load screen repeats indefinitely,I don't know whether this is caused by Patchouli, could you please help analyze it?
[debug.log](https://github.com/Vazkii/Patchouli/files/4398880/debug.log)

**Comment by williewillus** [comment]
This happens when another mod crashes during classloading at startup, patchouli is not the root cause. Try removing and readding half the mods each time to narrow down the suspect.
