### ISSUE TITLE
Game crashes when opening Spice of Life's food book

### ISSUE THREAD

**Issue by RisingInIris2017** [Vazkii/Patchouli#216]
#### Mod version:
Patchouli-1.15.2-1.2-31

#### Forge version:

1.15.2-31.1.41

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:
Attached in the crash-report.

## Link to full crash log
https://paste.ubuntu.com/p/WdzXS74CJh/

### How to reproduce
1. Install Patchouli and [Spice of Life: Carrot Edition](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/) mod.
2. Change Game language to `zh_CN`,or `中文（中国）`.
3. Open Food Book of Spice of Life.
4. Game crash.

This issue seems to be weird.
I have reported this issue to Spice of Life's dev.
https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues/87
And I think it is helpful to report to you.
Thanks for your kind help in advance!

**Comment by juliand665** [comment]
I'm really curious how Patchouli plays into this, since it doesn't seem to be involved in the stack trace at all… It looks like that topmost method in the stack trace (in `Char2ObjectOpenHashMap`) is crashing because the map is empty, so perhaps patchouli affects that somehow?

**Comment by RisingInIris2017** [comment]
I have tried the latest Patchouli 1.15.2-1.2-32 version,
but game still crash, and the way to reproduce is the same as I have mentioned above.
Maybe this issue is not solved yet.
https://paste.ubuntu.com/p/rM8hJct2XS/

**Comment by HelloCard** [comment]
still happened at solcarrot-1.21.1-1.16.3 and Patchouli-1.21-87-NEOFORGE only:
https://pastebin.com/m9qF2fEE
