### ISSUE TITLE
When I upload the mod on Twitch app it goes on the fabric version

### ISSUE THREAD

**Issue by Tauma-png** [Vazkii/Patchouli#217]
Everyday it keeps telling me there is an update of Patchouli, and when I'm tryin to it goes on the fabric version and so it makes my game stop, is there possible to create a page for the forge and the fabric version?

**Comment by williewillus** [comment]
Did it happen before or just this update? I set the Fabric version as a Release this time around but I can downgrade it back to Alpha/Beta to get the forge version to show up

**Comment by Tauma-png** [comment]
only this update, cause the previous version of the fabric was an alpha and so it didnt show up like you said

**Comment by mjlmjl888** [comment]
To fix this I have seen modders upload a fabric version as a whole other mod.

**Comment by williewillus** [comment]
I put the fabric version back to alpha.
I'd rather not have to make a whole new project to be honest, CF just needs to fix their stuff.
