### ISSUE TITLE
Issue with Polish characters

### ISSUE THREAD

**Issue by PanSzelescik** [Vazkii/Patchouli#22]
![image](https://user-images.githubusercontent.com/26679785/48425414-17189400-e765-11e8-9c2d-2c93c54eba14.png)

Here is okay:
![image](https://user-images.githubusercontent.com/26679785/48434401-e7c05200-e779-11e8-83cd-7400d5e70aba.png)

Code of this page: https://github.com/PanSzelescik/coolgadgets/blob/master/1.12/src/main/resources/assets/coolgadgets/patchouli_books/book/pl_pl/entries/items/calculator.json

Minecraft: 1.12.2
Forge: 2772
Patchouli: 1.0-6

**Comment by stanhebben** [comment]
Special characters should work, even Chinese has been tested. Are you sure the file is saved as UTF-8?

**Comment by PanSzelescik** [comment]
![adnotacja](https://user-images.githubusercontent.com/26679785/48428487-6bbf0d80-e76b-11e8-9252-568adc694389.png)
In my opinion, yes

**Comment by Vazkii** [comment]
Give this a try after the next version and let me know if it works better then.

**Comment by PanSzelescik** [comment]
Tested with 1.0-7.12 from maven. The same situation
![image](https://user-images.githubusercontent.com/26679785/48434141-3a4d3e80-e779-11e8-85a8-d2314b78e973.png)

**Comment by stanhebben** [comment]
It does work for me:

![afbeelding](https://user-images.githubusercontent.com/4592120/48449397-9aa4a600-e7a2-11e8-8466-002e422f7749.png)

**Comment by stanhebben** [comment]
I propose keeping this open until validated as fixed.

**Comment by PanSzelescik** [comment]
I redownloaded all my files from GitHub, built and situation is the same. I am wondering what you using for editing text? (Notepad++, Notepad from Windows or other?)

**Comment by stanhebben** [comment]
We believe the issue has been found and would be platform-dependent. I will implement the fix this evening and will let you know when it should be fixed.

**Comment by PanSzelescik** [comment]
I can't build Patchouli from GitHub, this package: https://github.com/Vazkii/Patchouli/blob/master/src/main/java/vazkii/patchouli/client/book/BookContents.java#L31 doesn't exist

**Comment by PanSzelescik** [comment]
I removed this import because is unused, and I can now build. It's working :) thanks ;)
![image](https://user-images.githubusercontent.com/26679785/48502888-f0c82680-e840-11e8-8206-d0abd02a447b.png)
