### ISSUE TITLE
[1.15 Fabric] BookRightClick crash on Mac

### ISSUE THREAD

**Issue by QuasiCastle7479** [Vazkii/Patchouli#220]
[crash-2020-04-13_15.48.27-client.txt](https://github.com/Vazkii/Patchouli/files/4471502/crash-2020-04-13_15.48.27-client.txt)

**Comment by i509VCB** [comment]
@QuasiCastle7479 could you also list some more details, OS, mods installed, etc.

**Comment by AK9Official** [comment]
@i509VCB It's AOF2 v2.10.2

**Comment by AK9Official** [comment]
Info to note:
https://i.imgur.com/M3zZTCt.png

**Comment by williewillus** [comment]
this should be fixed in recent builds
