### ISSUE TITLE
[1.15.2] crash botany book

### ISSUE THREAD

**Issue by HightWolt** [Vazkii/Patchouli#221]
Crashes when I open a book from botany
 
https://paste.ubuntu.com/p/KJP9NGDqTQ/

**Comment by XanTheMan123** [comment]
I'm having a similar issue. Before even attempting to open the book, just having the book in my active item slot causes a crash.
[crash-2020-04-18_22.15.21-client.txt](https://github.com/Vazkii/Patchouli/files/4498262/crash-2020-04-18_22.15.21-client.txt)

**Comment by HightWolt** [comment]
I have only when you click

**Comment by williewillus** [comment]
@HightWolt can you send the full debug.log. This happens when books have bad contents, and usually is not a patchouli issue (though patchouli could add more safety checks)

**Comment by HightWolt** [comment]
> @HightWolt можно отправить полную отладку.бревно. Это происходит, когда книги имеют плохое содержание, и обычно не является проблемой пачули (хотя пачули может добавить больше проверок безопасности)

https://paste.ubuntu.com/p/wwnBqzgY8v/

**Comment by HightWolt** [comment]
@williewillus  https://paste.ubuntu.com/p/wwnBqzgY8v/

**Comment by HightWolt** [comment]
@williewillus Well? Is there any progress?
