### ISSUE TITLE
Visualization not showing with botania installed

### ISSUE THREAD

**Issue by 3ddyy** [Vazkii/Patchouli#23]
All visualizations from Nature's Aura do not show any blocks when Botania is installed.

Full modlist:
AutoRegLib 1.3-20
Baubles-1.12.2 1.5.2
Botania r1.10-357
Nature's Aura b1
Neat 1.4-17
Patchouli 1.0-6
Quark r1.5-130
Quark Oddities

Forge version: 14.23.5.2768

Removing Botania fixes the issue

**Comment by Vazkii** [comment]
@williewillus, gonna pass this one to your plate.

**Comment by Vazkii** [comment]
Let me know if the next update solves this. It probably won't but just in case

**Comment by 3ddyy** [comment]
Updating Patchouli to 1.0-7 fixed the issue.

**Comment by Vazkii** [comment]
Could you mind going an extra step for me and trying to verify whether it
fixed the other open issue with thaumcraft?
