### ISSUE TITLE
Minecraft can't start

### ISSUE THREAD

**Issue by bubbaryebread** [Vazkii/Patchouli#243]
I currently run Fabric because my computer can't run Forge very well, and I tried using patchouli to run with other mods I have that use it for guidebooks. When I hit play on the Minecraft launcher, I immediately receive a message that says the game crashed. I don't get any more information than that like a log or anything, but the game starts just fine when I remove the patchouli file. Is there something I can do that will help or does there need to be an updated file?

**Comment by Oaklizard-2047** [comment]
Check your book files for any errors, like missing coma or something

**Comment by bubbaryebread** [comment]
Forgive me for not knowing, but I'm not great with mods and files for the most part. Should I open the mod file to look for errors? If so how would I tell what the errors are?

**Comment by Oaklizard-2047** [comment]
Check your json files. See if there's typos. Its in your book folder.
