### ISSUE TITLE
Loading I hit Patchouli and crashed 

### ISSUE THREAD

**Issue by Kingofgames319** [Vazkii/Patchouli#251]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Patchouli (patchouli)
[crash-2020-06-07_18.54.30-client.txt](https://github.com/Vazkii/Patchouli/files/4743188/crash-2020-06-07_18.54.30-client.txt)

**Comment by williewillus** [comment]
delete `patchouli_data.json` from your instance folder (`.minecraft`) and restart the game
