### ISSUE TITLE
[1.15.2] Nature's Aura: Locking book progress previously unlocked 

### ISSUE THREAD

**Issue by TTRazzix** [Vazkii/Patchouli#252]
The mod is locking chapters of the recieved book that were previously unlocked by doing advancements in the mod. Since the advancements can't be done twice, the chapters have no way of unlocking themselves afterwards.

The locking up happens whenever i log in the next time after completing chapters

**Comment by WolfBV** [comment]
It an issue since March 16th no stale pls

**Comment by WolfBV** [comment]
Bump
