### ISSUE TITLE
Feature Requirement - Seperate Project Repository Used on Twitch

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Vazkii/Patchouli#254]
**Describe the bug**
Twitch cannot differentiate file styles between fabric and forge so it falsely assumes there is an update. As a modpack manager this is aweful!

**To Reproduce**
Make a project.
Name it.
Make a zip made for forge
Make a zip made for fabric
Only latest can be seen.

**Expected behavior**
Making two seperate project pages. Example 
* Patchouli Forge
* Patchouli Fabric

![image](https://user-images.githubusercontent.com/10351221/84763459-d6f94300-af91-11ea-8064-7ca67033014d.png)

 Example of what users see.

**Comment by P3rf3ctXZer0** [comment]
Upvote!

**Comment by williewillus** [comment]
There are separate projects for forge and fabric now
forge: https://www.curseforge.com/minecraft/mc-mods/patchouli
fabric: https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric

**Comment by P3rf3ctXZer0** [comment]
thank you.
