### ISSUE TITLE
[1.16 Fabric] Text wrapping and spacing always uses blocky font sizes

### ISSUE THREAD

**Issue by Shnupbups** [Vazkii/Patchouli#256]
Regardless of whether a book has `use_blocky_font` set to `true` or left with the default `false`, text in the book will be line-wrapped and spaced as if it is `true`. This means that text will usually look rather odd.

With the default slim font (problem is visible)
![With the default slim font (problem is visible)](https://user-images.githubusercontent.com/2484721/84862810-30a75d80-b0b7-11ea-8b0b-d0ad3b726a8f.png)

With the blocky vanilla font (problem is mitigated)
![With the blocky vanilla font (problem is mitigated)](https://user-images.githubusercontent.com/2484721/84862847-3f8e1000-b0b7-11ea-8c74-a976b32cde93.png)

**Comment by williewillus** [comment]
fixed

**Comment by gousisme** [comment]
I'm having this problem in 1.19.2 for forge
