### ISSUE TITLE
Same Render Issue Just posting my logs

### ISSUE THREAD

**Issue by Divinesmiter** [Vazkii/Patchouli#257]
[crash-2020-06-17_13.08.22-client.txt](https://github.com/Vazkii/Patchouli/files/4794388/crash-2020-06-17_13.08.22-client.txt)

**Comment by TBiscuit1** [comment]
Have the same issue, posting my log, the more log, the easier is to correct a crash
[crash-2020-06-29_17.02.08-client.txt](https://github.com/Vazkii/Patchouli/files/4848020/crash-2020-06-29_17.02.08-client.txt)

**Comment by TBiscuit1** [comment]
Find out that Simple Ore and Patchouli together is causing the crash...

**Comment by williewillus** [comment]
I need the `debug.log` from both of you, not just the crash.txt
