### ISSUE TITLE
sync maven releases with cf releases

### ISSUE THREAD

**Issue by Linguardium** [Vazkii/Patchouli#263]
Fabric mod makers are relying on maven versions to be released to prevent crashing. Recently several features were added and maven picked up the new version but the version was not released to CF. 

This causes crashes when users have the current CF version and the mod relies on a the newer maven version. 

The mod devs have told me that i need to ask you to push releases to CF to prevent user crashing when using their mod with your current released version.

**Comment by williewillus** [comment]
Maven builds are not "releases", and modders should not be releasing mods that depend on unreleased versions of Patchouli

(I realize we're partially at fault for making breaking changes, but that's beside the point)

I'll make a release later today.

**Comment by Linguardium** [comment]
Thank you. I had that conversation but was effectively told that it being in the maven made it released and so its up to the user to bug you for a cf release.
