### ISSUE TITLE
[Fabric] Comma-separated items stopped working

### ISSUE THREAD

**Issue by MaryWeeb** [Vazkii/Patchouli#275]
In a recent version, comma-separated item identifiers stopped working in templates, giving the following error:
```
Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: composing:small_earth_crystal,composing
	at net.minecraft.util.Identifier.<init>(Identifier:41) ~[?:?]
	at net.minecraft.util.Identifier.<init>(Identifier:50) ~[?:?]
	at vazkii.patchouli.common.util.ItemStackUtil.loadStackFromString(ItemStackUtil.java:74) ~[Patchouli-1.16-38-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.variable.ItemStackVariableSerializer.fromJson(ItemStackVariableSerializer.java:18) ~[Patchouli-1.16-38-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.variable.ItemStackVariableSerializer.fromJson(ItemStackVariableSerializer.java:11) ~[Patchouli-1.16-38-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.variable.Variable.as(Variable.java:36) ~[Patchouli-1.16-38-FABRIC.jar:?]
```
<details><summary>template</summary>
<pre><code>
{
  "components": [
    {
      "type": "image",
      "image": "composing:textures/misc/patchouli_composing.png",
      "texture_width": 176,
      "texture_height": 182,
      "width": 176,
      "height": 182,
      "scale": 0.66
    },
    {
      "type": "item",
      "item": "#slot1",
      "x": 6,
      "y": 54
    },
    {
      "type": "item",
      "item": "#slot2",
      "x": 50,
      "y": 7
    },
    {
      "type": "item",
      "item": "#slot3",
      "x": 94,
      "y": 54
    },
    {
      "type": "item",
      "item": "#center",
      "x": 50,
      "y": 54
    },
    {
      "type": "text",
      "text": "#text",
      "x": 0,
      "y": 130
    }
  ]
}
</code></pre>
</details>
<details><summary>Erroring usage</summary>
<pre><code>
{
  "name": "Weapons",
  "icon": "minecraft:diamond_sword",
  "category": "effects",
  "pages": [
    {
      "type": "text",
      "text": "Here you can find a list of all composing effects that can be put on weapons. Note that the final upgrade only has a 50% success rate."
    },
    {
      "type": "composing",
      "slot1": "composing:small_earth_crystal,composing:medium_earth_crystal,composing:large_earth_crystal,composing:large_earth_crystal",
      "slot2": "composing:blessing_stone,composing:blessing_stone,composing:soul_stone,composing:holy_stone",
      "slot3": "composing:small_fire_crystal,composing:medium_fire_crystal,composing:large_fire_crystal,composing:large_fire_crystal",
      "center": "minecraft:diamond_sword",
      "text": "Attack damage (n)"
    },
    {
      "type": "composing",
      "slot1": "composing:small_earth_crystal,composing:medium_earth_crystal,composing:large_earth_crystal,composing:large_earth_crystal",
      "slot2": "composing:blessing_stone,composing:blessing_stone,composing:soul_stone,composing:holy_stone",
      "slot3": "composing:small_wind_crystal,composing:medium_wind_crystal,composing:large_wind_crystal,composing:large_wind_crystal",
      "center": "minecraft:diamond_sword",
      "text": "Attack damage (mult)"
    },
    {
      "type": "composing",
      "slot1": "composing:small_water_crystal,composing:medium_water_crystal,composing:large_water_crystal,composing:large_water_crystal",
      "slot2": "composing:blessing_stone,composing:blessing_stone,composing:soul_stone,composing:holy_stone",
      "slot3": "composing:small_water_crystal,composing:medium_water_crystal,composing:large_water_crystal,composing:large_water_crystal",
      "center": "minecraft:diamond_sword",
      "text": "Looting (n)"
    }
  ]
}

</code></pre>
</details>

**Comment by williewillus** [comment]
Can you show the json (and code, if applicable) for your `composing` template?

**Comment by martmists** [comment]
The template is there, see the folded "template"

**Comment by williewillus** [comment]
can you try with 1.16-39? A quite major bug in porting was discovered and fixed
