### ISSUE TITLE
[1.15.2] Crafttweaker recipes not showing in book

### ISSUE THREAD

**Issue by teagan75** [Vazkii/Patchouli#276]
Any recipe added or changed in crafttweaker is not showing while using the crafting entry page type. It isn't erroring out either.

**Comment by williewillus** [comment]
Does CT change the recipe ID?

**Comment by teagan75** [comment]
Yes it does. Sorry about that. Closing this out.

**Comment by teagan75** [comment]
Actually reopening. I used the new id and it still won't show up.
![2020-07-26_15 05 45](https://user-images.githubusercontent.com/12485764/88488252-94903200-cf51-11ea-917a-3e5d049a0992.png)
![2020-07-26_15 05 51](https://user-images.githubusercontent.com/12485764/88488253-95c15f00-cf51-11ea-9785-79790bc7d424.png)

**Comment by teagan75** [comment]
nevermind I am an idiot :)
