### ISSUE TITLE
Custom Title Screen Crashing [Fabric]

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Vazkii/Patchouli#277]
When running Patchouli with CustomTitleScreen on Twitch causes the game to crash before loading.

The game doesn't generate crash_report so here is the log file.
[latest.log](https://github.com/Vazkii/Patchouli/files/4978876/latest.5.log)

**Comment by williewillus** [comment]
Have you tried reproducing in a more minimal environment?
For example:
* Try with just Patchouli or CTS by itself, then together with no other mods
* Try in multimc without jumploader
* Combination of the above two

A brief scan of the log looks like a mixin failure in CTS, but the failure is in code that Patchouli doesn't touch.
