### ISSUE TITLE
[1.16] Patchouli won't load on the latest Forge

### ISSUE THREAD

**Issue by FynnWaelsing** [Vazkii/Patchouli#278]
Patchouli version: Patchouli-1.16-39
Forge version: 32.0.93
latest log: https://pastebin.com/Dmes4L56

Getting an error message that Patchouli hasn't loaded correctly on the latest (93) version of Forge. The mod loads correctly on version 88.

**Comment by williewillus** [comment]
it's a bug in forge. downgrade a couple versions for now until they fix it

**Comment by Yunus1903** [comment]
This has been fixed as of Forge 32.0.95
