### ISSUE TITLE
[Forge 1.16] The book won't reload in-game

### ISSUE THREAD

**Issue by Extegral** [Vazkii/Patchouli#281]
I am using **Patchouli 1.16-39** and **Forge 32.0.67**. Just started figuring out how basic stuff works, and ran into an issue: Shift+Right-clicking on Editor button on my newly created book's title page doesn't seem to do anything at all. I double checked to make sure that Minecraft uses updated resources and datapacks after I change them, and it seems to be the case since I can freely change crafting recipes, advancements etc. of my mod and /reload command brings up those changes.

Patchouli, however, doesn't seem to react in any way to datapack changes, and book stays unaltered until client re-launch, which is, needless to say, isn't super convenient.

My book's implementation doesn't have anything special, for the most part I've been following instructions on the Wiki and so far it consists of only main book.json file, that looks like this:

```
{
	"name": "The Aknowledgment",
	"landing_text": "Completely random text",
	"version": 1,
	"creative_tab": "enigmaticCreativeTab",
	"use_blocky_font": "true"
}
```

...besides `en_us/categories`, `en_us/entries` and `en_us/templates` folders in the same place that are yet empty.

**Comment by williewillus** [comment]
is this for a mod or pack?

**Comment by williewillus** [comment]
also, book.json cannot be hot-reloaded, actually content can

**Comment by Extegral** [comment]
> is this for a mod or pack?

I seems to have mentioned that I'm making a mod. When referring to datapack, I meant mod-embedded datapack, since, well, that's what it is.

> also, book.json cannot be hot-reloaded, actually content can

Oh, now that explains everything. Sorry for not realizing, guess case closed then.
