### ISSUE TITLE
I can't find the book

### ISSUE THREAD

**Issue by emanuele246gi** [Vazkii/Patchouli#283]
Until now i was able to find the book, write on it and so on. Today I wanted to continue editing it but I couldn't find it anywhere despite still having all the files and folders in the right place :/
What happened?

Minecraft Version: 1.15.2
Forge Version: 31.2.36
Patchouli Version: 1.2-35

**Comment by williewillus** [comment]
ask on discord #help for assistance with your book, this tracker is for bugs only

**Comment by emanuele246gi** [comment]
Thanks
