### ISSUE TITLE
So this is happening...

### ISSUE THREAD

**Issue by GabuSilver** [Vazkii/Patchouli#294]
Im using 1.15.2 most latest botania version (388th) and Lexica Botania (Both the "apprentice"/green borders and "master"/golden borders) is having this issue; where every documentation has "[]" symbols. I probably better do almost copy paste thing at Patchouli too

[https://imgur.com/b71jZK5](url) <---- Proof

**Comment by Hubry** [comment]
#236 (it's the pinned issue!)
