### ISSUE TITLE
Having an issue with 1.15.2 Botania 388th Edition

### ISSUE THREAD

**Issue by GabuSilver** [Vazkii/Patchouli#295]
Im using 1.15.2 most latest botania version (388th) and Lexica Botania (Both the "apprentice"/green borders and "master"/golden borders) is having this issue; where every documentation has "[]" symbols.

https://imgur.com/b71jZK5 <---- Proof

**Comment by Hubry** [comment]
#236 (and why did you double post?)

**Comment by GabuSilver** [comment]
0.0 My biggest apologies I though I posted on Botania Issue thing!
