### ISSUE TITLE
[1.15.2] Using Player Heads Crashes Game

### ISSUE THREAD

**Issue by ShinyPorygon** [Vazkii/Patchouli#307]
So, I'm writing a patchouli book for Thermal Expansion along with others and for the contributers I was going to put their Minecraft skin but once you open the book, and click on the category where those are located the game instantly crashes.

Edit: Under Drullkus's request I added a copy of the json that was doing it

Log https://pastebin.com/F5cCGkSq

Versions: 
Forge:  31.2.41
[examplejson.zip](https://github.com/Vazkii/Patchouli/files/5258267/examplejson.zip)

Patchoulli - 1.15.2- 1.2-35

**Comment by ShinyPorygon** [comment]
User Error (Thanks Drullkus)

**Comment by williewillus** [comment]
what was the problem? User error still shouldn't crash the game so we're interested in shoring up error handling in modern versions

**Comment by ShinyPorygon** [comment]
Well, since you insist, the problem seemed to exist because when I copy pasted the base minecraft head getting command, I had kept an extra space before the whole line so it was " minecraft_head(ect ect)" And that caused it crashing beyond oblivion

**Comment by williewillus** [comment]
Cool thanks
