### ISSUE TITLE
Vote Screen

### ISSUE THREAD

**Issue by alexis-evelyn** [Vazkii/Patchouli#308]
Can we not have this in the mod? Or at least have a version without it? I don't need this showing up everytime I do something in my dev environment and besides Minecraft is my break from thinking about politics. I already hear/think about it enough outside of Minecraft.

![Screen Shot 2020-09-24 at 1 43 21 AM](https://user-images.githubusercontent.com/6305346/94106184-e1d13880-fe08-11ea-904a-0bd767a20f43.png)

**Comment by williewillus** [comment]
> everytime I do something

it shows up literally once.
