### ISSUE TITLE
Bold text overlaps with following non-bold text

### ISSUE THREAD

**Issue by zabi94** [Vazkii/Patchouli#31]
I noticed this bug while browsing through the default books (the SCP reference page) while adding Italian localization.  

I was working with commit ec82535568b7cd5b5733373e7cf9b09c7c0b011e  
It was in a dev env (Eclipse in Ubuntu).  

I'll attach a screenshot for clarity
![2018-11-14_11 39 42](https://user-images.githubusercontent.com/11521878/48478306-31ee1580-e804-11e8-9b67-e87f6ffde7ec.png)

**Comment by stanhebben** [comment]
This might be a bug in the new text renderer; my fault.
