### ISSUE TITLE
Problem with additional ":" in multiblock page.

### ISSUE THREAD

**Issue by Liiw** [Vazkii/Patchouli#312]
Hello! I would like to create a multiblock page that would showcase some samples and ores from Geolosys. I tried doing it this way: 

`{
                "mapping": 
                {
                    "B": "geolosys:ore_sample:2",
                    "A": "geolosys:ore_3",
                    "N": "geolosys:ore_sample:2",
                    "M": "geolosys:ore:2",
                    "E": "minecraft:grass"
                },
                "pattern":
                [
                    ["   ","   ","   "],
                    ["B  ","BN0","A  "],
                    ["EEE","EEE","EEE"]
                ]
            }`

Unfortunately the blocks with that additional ":" (I don't know how to call these formats) in the name will not get rendered. Is there another way to handle this?

**Comment by williewillus** [comment]
blocks should not have trailing `:2` names, ever.

If you are wanting to set blockstate properties, use syntax like `minecraft:note_block[note=4]` (the same way you would pass it to setblock)

**Comment by Liiw** [comment]
Thank you for your answer! So I understand the bit behind the last ":" is a blockstate? How would I know what kind of blockstate for example "geolosys:ore:3" is or where should I look for that info?

**Comment by Liiw** [comment]
So after searching around, I have learned that regarding Geolosys blocks, the blockstate property is [variant=...]. Thank you for your time!

**Comment by williewillus** [comment]
no prob.

For future reference you can use the F3 screen top right corner. It shows the block ID `minecraft:note_block` then all the properties one by one `note: 4`. You'd take the ID, then append all the properties in alphabetic order, enclosed by brackets.

See https://minecraft.gamepedia.com/Commands#.3Cblock.3E
