### ISSUE TITLE
Crash displaying tooltip

### ISSUE THREAD

**Issue by xBoBx78** [Vazkii/Patchouli#313]
Anytime I hover over anything in my inventory game crashes. (New game).

Minecraft Version: 1.15.2
Modpack: ATM5
Patchouli Version: Patchouli-1.15.2-1.2-35
[debug.log](https://github.com/Vazkii/Patchouli/files/5309819/debug.log)

**Comment by Tomodachi94** [comment]
Could you please post the latest log in the `crash-reports` folder in your `.minecraft` folder, on a site like [gist.github.com](gist.github.com) and post it?

**Comment by williewillus** [comment]
`debug.log` from the `logs` folder would be better
