### ISSUE TITLE
Book texture broken 1.16.3

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Vazkii/Patchouli#316]
The texture for Patchouli books in 1.16.3 is broken. I've also tried the alternate book_texture in the book.json file. This also affects all mods that use Patchouli.

Minecraft: 1.16.3
Forge: 34.1.19
Patchouli: 1.16.2-44

`[m[33m[12:02:24] [Render thread/WARN] [patchouli/]: You're trying to deserialize an object of type interface net.minecraft.util.text.ITextComponent from one of type class net.minecraft.util.text.TranslationTextComponent. This is likely not what you want!`

![2020-10-14_13 42 10](https://user-images.githubusercontent.com/17887664/96037446-17bf7680-0e23-11eb-85a2-f5ec03c3d02b.png)

![2020-10-08_20 06 54](https://user-images.githubusercontent.com/17887664/96037531-33c31800-0e23-11eb-8e61-638954d6146c.png)

**Comment by Txsa** [comment]
I have the same issue. Is there a way to check if this is the mod looking in the wrong place or an issue with the texture?

**Comment by ClaudiusMinimus** [comment]
Just tried Patchouli-1.16.2-45 and it is still not rendering

**Comment by williewillus** [comment]
please try https://ci.blamejared.com/job/Patchouli/job/master/232/artifact/build/libs/Patchouli-1.16.2-46-SNAPSHOT.jar and see if it helps

NOTE: this is a pre-release/unstable version, don't use it for anything other than testing.

**Comment by williewillus** [comment]
Fixed in 1.16.2-46
