### ISSUE TITLE
UI size option doesn't seem to be working

### ISSUE THREAD

**Issue by zabi94** [Vazkii/Patchouli#32]
The UI Scale option when the game starts is "default". Clicking it once switches it to "medium" without changing anything, further clicks have no effect. Tested on both a custom book and a default test book.  

I was running code from ec82535568b7cd5b5733373e7cf9b09c7c0b011e, but it had the same problem with the maven jar 1.0-7.9.  
Run in Eclipse under Ubuntu.

**Comment by stanhebben** [comment]
Apparently at such small screen size there is also only the medium option. This has been changed so that if there is no option, the resize button isn't shown either. Also, if the largest option has been reached, the button will now go back to default size instead of medium.
