### ISSUE TITLE
[1.16.4][Forge] Mixin apply failed

### ISSUE THREAD

**Issue by Zorochase** [Vazkii/Patchouli#320]
Trying to integrate Patchouli into my mod; added the repository and dependencies to my build.gradle file. However, when I run the game, and try to load a world, loading ends up stuck on 100%. The game doesn't crash though, so I have no crashlog to provide. However, the error reported is [here](https://pastebin.com/raw/5RUpW5dT). I've changed nothing about Patchouli's source, and I was testing on a stable version of my own mod. All I've done is added the maven repository and dependencies to my build.gradle file.

Versions: Patchouli 1.16.2-47 / Forge 35.0.1
MC 1.16.4

**Comment by williewillus** [comment]
have you read https://github.com/Vazkii/Patchouli#mixin-troubleshooting?

**Comment by Zorochase** [comment]
I have. I may be doing it wrong (and I apologize if I am, I'm somewhat new to modding in general), but I placed the line `property 'mixin.env.disableRefMap', 'true'` inside my [build.gradle](https://github.com/Zorochase/NeoArsenal/blob/0e95e4fee80a46405486b7d0950f612f3e604db2/build.gradle#L46) file, but it didn't do anything, the same issue persisted. I don't know where else to put this, or how else it should be written. Again, I apologize if this is me making a noob mistake.

**Comment by Extegral** [comment]
Well, my own project currently depends on Patchouli and I have no issues with disabling refmaps. The actual line I use to disable it differs a bit from yours though:
https://github.com/Extegral/Enigmatic-Legacy/blob/1c56e9374b0737b510e92fd9b1b63eee7b4b5f2c/build.gradle#L54
Not sure if that matters but you can try changing it to that.

**Comment by Zorochase** [comment]
That didn't do anything either, I still got the same error. I don't know what I'm missing, if anything at all.

**Comment by Extegral** [comment]
I dunno, are you sure you're not doing something dumb? (like starting client instance from within Eclipse rather than command line)

**Comment by Zorochase** [comment]
Well I'm using IntelliJ, but yeah I am starting it from within the IDE using configurations. That's how I've been doing it and I haven't run into problems doing it that way until now. I don't really even know how to start the client instance via the command line manually..

**Comment by Extegral** [comment]
Using IDE runs is not an issue on itself, but I suspect you just never updated your runs after generating them. Use `gradlew genIntellijRuns` (or whatever is it, not sure I remeber exactly) to re-generate your runs anytime you do any tweaks to runs in your `build.gradle`. Ideally you should do this even when you just update Forge/MCP or do any major changes in general.

**Comment by williewillus** [comment]
^
