### ISSUE TITLE
stuttering entry highlighting

### ISSUE THREAD

**Issue by GamerXD8991** [Vazkii/Patchouli#323]
Patchouli Version: Patchouli-1.16.2-47
Forge Version: 35.0.14
MC: 1.16.4

when hovering over an entry the "loading bar" highlighting stutters extremly happens with multiple books from differnt mods. (so far seen/tested with Ars Noveau, Industrial Forgoing and Psi)

**Comment by williewillus** [comment]
can you try with just patchouli and one other mod using it

**Comment by GamerXD8991** [comment]
using geckolib 2.1.2 (as 3.0 beta 8 causes crashing on startup) and only Ars Noveau the stuttering still happens. (a bit less thou but that could be my imagination)

a second test using only Botania (409) shows stuttering as well (about the same amount as I originally saw when opening the issue)
