### ISSUE TITLE
[1.15.2]Config Flags will be cleared after setting

### ISSUE THREAD

**Issue by SihenZhang** [Vazkii/Patchouli#325]
Config Flags will be cleared after setting so that the custom flag will not be valid.
https://github.com/Vazkii/Patchouli/blob/0bd0497308d574cb23cc25934832289d13b231b9/src/main/java/vazkii/patchouli/common/base/PatchouliConfig.java#L32-L37
But in 1.16, it will not be cleared.
https://github.com/Vazkii/Patchouli/blob/4ddfbfc8b5270559577fed09f9faeb748e7afa51/src/main/java/vazkii/patchouli/common/base/PatchouliConfig.java#L30-L34
I don't know if this is my problem. So I want to know when should I set my custom Config Flags.

**Comment by williewillus** [comment]
1.15 behavior is a bug

**Comment by SihenZhang** [comment]
So will it be fixed later? If it will not be fixed in 1.15.2, is there another solution?

**Comment by williewillus** [comment]
update to 1.16
