### ISSUE TITLE
"smelting" page show only text

### ISSUE THREAD

**Issue by timearrow03** [Vazkii/Patchouli#332]
I was trying to add a smelting page to my book but it doesn't show any graphics or recipe only an empty space followed by the page text ("sand smelt into glass")

This is my page json:

        {
            "type": "smelting",
            "recipe": "minecraft:sand",
            "title": "smelt  sand",
            "text": "sand smelt into glass"
        }

**Comment by williewillus** [comment]
full json + version info please

**Comment by timearrow03** [comment]
This is the page, I've tested blasting too with the same result:

{
    "name": "test page",
    "icon": "minecraft:sand",
    "category": "examplemod:test",
    "read_by_default": true,
    "pages": [
        {
            "type": "smelting",
            "recipe": "minecraft:sand",
            "title": "smelt sand",
            "text": "sand smelt into glass"
        },
        {
            "type": "blasting",
            "recipe": "minecraft:emerald_ore",
            "title": "blast sand",
            "text": "emerald ore blast into emeralds"
        }
    ]
}

I'm using patchouli version1.16.4-48-SNAPSHOT. No errors in the log

**Comment by timearrow03** [comment]
this is a snap of what the pages look like in the book:

![snap](https://user-images.githubusercontent.com/75505269/101242878-a8685380-36fc-11eb-993c-5eec35626dcc.png)

**Comment by ZeroNoRyouki** [comment]
It's a documentation problem.

Because of how Patchouli load the recipe from MC RecipeManager, the ResourceLocation (recipe, recipe2) need to be the id of that particular recipe, not an "itemstack" containing the item being smelted. 

So, for your example, "minecraft:glass"

**Comment by timearrow03** [comment]
with minecraft:glass it works! thank you
