### ISSUE TITLE
Regression in item component parsing

### ISSUE THREAD

**Issue by Hubry** [Vazkii/Patchouli#334]
Before #225, item components were parsed as follows: 
https://github.com/Vazkii/Patchouli/blob/f92d742448a59009e63cdc647ebeb7b21a968985/src/main/java/vazkii/patchouli/client/book/template/component/ComponentItemStack.java#L29
After #225: 
https://github.com/Vazkii/Patchouli/blob/4ec3047d00b424da798f519399c10f9c2bc3f8e6/src/main/java/vazkii/patchouli/client/book/template/component/ComponentItemStack.java#L40

`ItemStackUtil#loadStackListFromString` contains a tag check, but the current way doesn't.
@Alwinfy smh

**Comment by Alwinfy** [comment]
https://github.com/Vazkii/Patchouli/blob/4ec3047d00b424da798f519399c10f9c2bc3f8e6/src/main/java/vazkii/patchouli/client/book/template/variable/ItemStackVariableSerializer.java#L17 ?

**Comment by Alwinfy** [comment]
oh wait never mind i see what you mean. that's kind of annoying to resolve, actually

**Comment by williewillus** [comment]
pog i can assign people
