### ISSUE TITLE
Itemstack component frame misaligned

### ISSUE THREAD

**Issue by Hekera** [Vazkii/Patchouli#337]
Itemstack component frames are no longer squashed, but are misaligned by one pixel left and up in version 1.16.4-48 for forge. 
![image](https://user-images.githubusercontent.com/40907168/101588774-1d65b280-39b5-11eb-88ac-e3f68d2c2a37.png)

**Comment by KingLemming** [comment]
Bump. Yep.

**Comment by williewillus** [comment]
should be fixed in 50
