### ISSUE TITLE
[Request] Ingredient Template Component

### ISSUE THREAD

**Issue by baileyholl** [Vazkii/Patchouli#340]
A template component that can take a serialized ingredient would be fantastic, with support for the itemstacks rotating through as they do in recipes.

It is currently impossible, to my knowledge, to display multiple valid items that could be used in your custome templated recipes, without using a modded component processor and a corresponding custom template component.

**Comment by williewillus** [comment]
I believe this is possible now with Alwinfy's improvements to itemstack deserialization
