### ISSUE TITLE
Failing to apply ClientAdvancementManager mixin

### ISSUE THREAD

**Issue by Termiantorng** [Vazkii/Patchouli#342]
The tile is pretty much all there's to it, the ClientAdvancementManager mixin fails to apppy.

This is the full error message:
`Mixin apply failed assets/patchouli/patchouli.mixins.json:client.MixinClientAdvancementManager -> net.minecraft.client.multiplayer.ClientAdvancementManager: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on patchouli_onSync could not find any targets matching 'Lnet/minecraft/client/multiplayer/ClientAdvancementManager;func_192799_a(Lnet/minecraft/network/play/server/SAdvancementInfoPacket;)V' in net.minecraft.client.multiplayer.ClientAdvancementManager. Using refmap patchouli.refmap.json [PREINJECT Applicator Phase -> assets/patchouli/patchouli.mixins.json:client.MixinClientAdvancementManager -> Prepare Injections ->  -> handler$zza000$patchouli_onSync(Lnet/minecraft/network/play/server/SAdvancementInfoPacket;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]`

Instead of crashing, the game just freezes while loading a world. 

I'm making a 1.16.4 forge mod, using the lastest maven build of Patchouli for forge, but I haven't made any books yet.

Please ask, if you need any more information.

**Comment by williewillus** [comment]
https://github.com/Vazkii/Patchouli#mixin-troubleshooting

**Comment by Termiantorng** [comment]
Looks like I have been an idiot once again
