### ISSUE TITLE
Patchouli is expensive when it comes to load time.

### ISSUE THREAD

**Issue by DatsiK96** [Vazkii/Patchouli#343]
Not sure if that's just the nature of the mod, but it's incredibly expensive, increasing the load times by like 30 seconds alone.

Is there anyway to remedy this?

**Comment by williewillus** [comment]
Need more details about this. What mods? Patchouli by itself? Version?

**Comment by DatsiK96** [comment]
Sorry, it was apparently only with other mods. I'm closing this.
