### ISSUE TITLE
Cannot open Patchouli books when in another player's claimed zone (FTB Chunks) [1.16]

### ISSUE THREAD

**Issue by wrincewind** [Vazkii/Patchouli#345]
FTB Teams 1604.1.0.13 and Patchouli 1.16.4-48 - when you're in someone else's claimed chunks, you cannot open any GUI. This is intended behaviour by FTB, but for some reason this seems to extend to the manuals (Lexica Botania, Blood Magic). This does not extend to e.g. the Astral Tome from Astral Sorcery. Joining the person's team solves the issue.

**Comment by wrincewind** [comment]
having checked with FTB Teams version 1604.1.0.15-forge and patchouli 1.16.4-48 (from the dw20 modpack), it's still an ongoing issue. Should I bring this to the FTB Teams' attention?

**Comment by williewillus** [comment]
I'd say so, yeah. If it's preventing any and all guis from opening, that seems like a problem. Can you even open a vanilla book in a claim?

**Comment by wrincewind** [comment]
After a little testing, i CAN open the following on a claimed chunk: 
- a vanilla book + quill (un-signed) 
- a MineColonies clipboard
- an Ars Nouveau spell book, 
- an Astral Sorcery Tome

but I can't open the following: 
- a vanilla written book (signed and completed)
- any patchouli guide
- a RS Addons Wireless Crafting grid
- an Ender Pouch
- or a simply backpacks backpack.

I'm not sure why some of these work and others don't; presumably they're calling different actions?

**Comment by Hubry** [comment]
I would assume that the ones that don't work execute the opening on the server side, telling the client to do the action with a packet. This is what Patchouli does - it specifically checks `player instanceof ServerPlayerEntity` in the use method.
