### ISSUE TITLE
Unable to load book via datapack

### ISSUE THREAD

**Issue by ChromaPIE** [Vazkii/Patchouli#355]
First, undoubtedly there's nothing wrong with the directory where I put the contents in and the usage of OpenLoader is believed to be correct, as the game do appears to detected the data pack and it loads recipes etc. just as expected, which I was hoping for the `patchouli_books` folder to be too.

The project I was working on for my personal use is the zh_cn localization for Thermal Series' Patchouli guidebook. I followed the [wiki](https://github.com/Darkhax-Minecraft/Open-Loader/wiki/Creating-Datapacks) of OpenLoader and built a directory to put stuff in. The `patchouli_books` folder was located under `.minecraft\openloader\data\thermal\data\thermal`, in which exists a `guidebook` folder, containing a `zh_cn` folder, and a `book.json`, strictly obbeying exactly the same structure in the Thermal Foundation (it's called simply Thermal now). All of the above are to prove that I didn't mess things up and already checked twice, well, at least I thought so.

The problem is, the changes to the JSONs won't in any ways be loaded to the game, even after a couple of times' /reload and reloading the book by shift clicking that button in the book GUI. Moreover, it's roughly tested that it can't be successfully loaded even in vanilla way, where you make it a zip and put it into `saves/WORLD/datapacks/`, then run a /reload. But no, it's not working.

However even after those tests and checks and reboots, it's still possible that something actually went wrong only on my end. Would be nice to have it checked officially.

**Comment by ChromaPIE** [comment]
I'm here just expecting for a simple reply informing me of any kinds of confirmation about whether this project is still active to make it tally with issues above and below that all got labels or comments. Could even close this issue then I'll be more than happier than checking this issue laying here like it's long buried for three or four times a day. Have anyone already tried duplicating this issue for god's sake comment below, all appreciations are yours.

**Comment by baka-gourd** [comment]
@Hubry Does this mean that loading books from mods becomes the only way to🤔

**Comment by Hubry** [comment]
I was assuming that someone actively working on this would answer this, but alas. I'm mostly just fixing whatever I personally hit when working on Botania or if I get a boost of motivation out of nowhere. All of us are just volunteers working on this in our free time.

There is the `patchouli_books` folder in the instance root. Use that. You can put a brand new book there, and you can provide a book extension there to edit an existing book.
Despite the book data going into `data`, it is not actually loaded from datapacks - in fact putting it there was a bit of a mistake on Vazkii's part during the 1.14 port, and we're kinda stuck with it. The only part that is really "data" is the `book.json`, which is the only piece loaded by the server side. Still, the mod comes with a loading mechanism for packmakers already, you don't need openloader or whatever unless you want custom images or if you want to use the langfile translation mode for the book.

This question would get a much faster answer if you asked in Discord, which I check far more than it's healthy for me, and has several other people lurking.

**Comment by ChromaPIE** [comment]
However the fact is that it's just not working. I just created a book in the patchouli_books folder under .minecraft, put an `extend` key after which the target book's modid and the path were followed, exactly obeying the form described in the wiki, in book.json, and created a category for testing, but it just not showing after a reboot, a /reload, and reloading the book. But even if I believe I didn't mess up a single step I still wondering if something's went wrong only on my end. Now I've already tried the vanilla datapack, the openloader datapack, the .minecraft/patchouli_books extension, none of them ever worked. The very original en_us book content is like being pinned by some kind of unknown omnipotent overwatching power preventing it from being overwritten by any 3rd party intervention.

**Comment by ChaosDogG** [comment]
I would like to bump this issue as I myself would love to use datapacks to make custom book entries! I'm not entirely sure if a custom book file can be uploaded onto server files as a server only sort of deal and players who get this mod will automatically find it, but that's just my opinion

**Comment by baka-gourd** [comment]
Under normal circumstances, the datapack is not loaded on the client side (only on the server side) and you can use resource pack distribution with [this](https://github.com/kappa-maintainer/PRP).

**Comment by williewillus** [comment]
Just a note that this is in the works with 1.17 Fabric now supporting books partially defined in the resource pack. See https://github.com/Vazkii/Patchouli/wiki/1.17-Update-Guide-for-Authors for more info

**Comment by sigmasoldi3r** [comment]
I know this topic is old but I can't find any solution (and almost all searches hit this thread).

I'm making a datapack, and tried manually loading it, using open loader... and nothing works. The only way I've got it working is via `.minecraft/patchouli_books` folder, but that is not a solution, just a workaround, and I would like to have it inside a datapack.

I don't know what can be wrong with my folder structure of the datapack (And yes, the datapack itself works because I've tried adding other things like resources, and works.)

<img width="354" height="440" alt="Image" src="https://github.com/user-attachments/assets/cdf1279c-04eb-4a19-8a17-9967ba993029" />

That is my structure, and I've followed the guide step by step... I don't know what I'm missing really.

PS: I'm using `Neoforge 1.20.4`, so the latest docs should work, right?

## Edit

I've just re-read @Hubry 's reply. So the only way of packing it is in a mod, right? I'll see if I have time to open a PR in the docs in that case, to make it more clear (like adding a note stating that, despite being the same structure as datapacks, it won't work, or something along the lines)
