### ISSUE TITLE
I can't seem to join my server with Patchouli's installed

### ISSUE THREAD

**Issue by DeinoWasHere** [Vazkii/Patchouli#363]
https://media.discordapp.net/attachments/665991753412902962/812130403313516544/Screenshot_25.png?width=1200&height=113

Sorry Im new to github and couldn't figure out how to upload an image

**Comment by williewillus** [comment]
it needs to be installed on both sides.

**Comment by DeinoWasHere** [comment]
it is installed on both sides and still shows the same thing

**Comment by williewillus** [comment]
Get on Discord and ask in #help

**Comment by DeinoWasHere** [comment]
Okay, can do thank you for the help!
