### ISSUE TITLE
"smelting" type not working for most modded items

### ISSUE THREAD

**Issue by KajesLorian** [Vazkii/Patchouli#364]
Minecraft 1.16.4
Forge: 35.1.36
Patchouli 1.16.4-48

**Issue:**
Using the "smelting" type works for vanilla items, but not for most modded items. Image is missing, though "text" shows up.

**Pastbin of entry:**
(Issue is at the bottom of page)
https://pastebin.com/KnbGVdU6

**Further info:**
I've tried many different items, both the finished item and the item it's smelted from. None of the items throw an error upon book reload.

What does work:
Vanilla
Refined Storage Silicon

What does not work: (not an exhaustive list)
Cooking for Blockheads recipe book (what I'm actually trying to link. Yes, it's smelted. Yes, it's weird to me too)
Create Copper
Mekanism Copper
Mekanism Osmium
Eidolon Lead
Extreme Reactors Yellorium
Druidcraft Rockroot
Quark Ender Biotite

**Comment by williewillus** [comment]
you don't put the item ID of the ingredient or result, you need to find the recipe ID. JEI shows you the recipe ID if you hover over the output.

**Comment by KajesLorian** [comment]
That solved it, and taught me how to get all the recipe IDs for myself. Thank you!
