### ISSUE TITLE
Patchouli causes Minecraft to crash on startup

### ISSUE THREAD

**Issue by Katoteshiku** [Vazkii/Patchouli#365]
Title says it all, whenever I launch Minecraft, it loads all the mods but when it reaches patchouli, it just stops and crashes

[pacthouli.txt](https://github.com/Vazkii/Patchouli/files/6014828/pacthouli.txt)

**Comment by Hubry** [comment]
Your `patchouli_data.json` (located in the instance root) file seems to be corrupted somehow, delete it.
