### ISSUE TITLE
New to json editing

### ISSUE THREAD

**Issue by razer1989-tech** [Vazkii/Patchouli#366]
I'm trying to use Patchouli to make a guidebook for a modpack, I keep getting errors in my test_entry about not having a valid category,
I'm trying to follow the wiki but it keeps  giving the same error
How do I Validate my category .json file? Or what am I doing wrong? Please help

**Comment by williewillus** [comment]
to check syntax, use an editor with json syntax highlighting, and put it through https://jsonlint.com/

**Comment by williewillus** [comment]
if it's a non syntax problem, the logs usually will tell you what's wrong.
