### ISSUE TITLE
Enable BuildCraft PEPO

### ISSUE THREAD

**Issue by ErythroCraft** [Vazkii/Patchouli#368]
Hi.

Most like BuildCraft.
But any updates are not fast of this mod.

Maybe you can folk the 

https://github.com/BuildCraft/BuildCraftGuide

**Comment by williewillus** [comment]
We don't have any control over what other projects do, it's their choice if they use patchouli or not (they seem to not)

**Comment by ErythroCraft** [comment]
https://gitter.im/jenkinsci/jenkins

**Comment by williewillus** [comment]
I have no idea what you're talking about.

**Comment by ErythroCraft** [comment]
Is ok.

Only the Idia was to implement a mod in Patchouli or Patchouli in BuildCraft.
But now it is closed by self.

Limit yourself to yourself and live healthy.
