### ISSUE TITLE
[Feature Request] The ability to represent "other" crafting methods

### ISSUE THREAD

**Issue by MightyBidoof** [Vazkii/Patchouli#37]
Simple request. A way to add non-standard recipes to a book, an example of what I mean is how the Lexica Botania handles showing the Terrasteel recipe.

The main use case for this is if you've added a custom Terrestrial Agglomeration Plate recipe using CraftTweaker + Botania Tweaks, and you'd simply like to display the recipe in a visual manner, _outside of JEI_, rather than listing off all the items needed for the recipe. There's mostly likely a few other use cases for this if it were implemented.

Alternatively allowing us to display any items we wish in the crafting table page type could also work, as it'd still be a visual method of displaying the necessary items and the output.

**Comment by Daomephsta** [comment]
Take a look at [templates](https://github.com/Vazkii/Patchouli/wiki/Using-Templates), you can use the `item` component to display items.
