### ISSUE TITLE
Image scaling is wrong

### ISSUE THREAD

**Issue by agentwolf88** [Vazkii/Patchouli#376]
When i add an image the scale of the picture is wrong. The picture is every time too large.

My picture is 256x256.

MC1.16.5
Forge 36.1.0

**Comment by Hubry** [comment]
Post screenshots and possibly even the json of the page.

**Comment by agentwolf88** [comment]
<img width="445" alt="Bildschirmfoto 2021-03-18 um 13 26 11" src="https://user-images.githubusercontent.com/9948479/111625813-944ceb80-87ed-11eb-9797-affb36a1e245.png">

Its a test picture 256x256. All image have the same bug.

{
	"name": "Areas",
	"icon": "minecraft:oak_sign",
	"category": "mods",

	"flag":"advancements_disabled",
	"priority":false,
	"secret":false,
	"read_by_default":false,

	"pages": [
	{
		"type": "text",
		"text": "Um ein Gebiet zu benennen muss man [Area] 10 auf ein Schild schreiben."
	},
	{
		"type": "text",
		"text": "Most of the pages for the default page types are organized into subcategories."
	},
	{
		"type": "image",
		"images":["buchdeswissens:images/areas/areas_1.png"],
		"title" : "Title of image",
		"border":true,
		"text": "Images used here should ideally be dimensioned as 256x256"
	}
 ]
}

**Comment by Hubry** [comment]
<https://github.com/Vazkii/Patchouli/wiki/Default-Page-Types#image-pages>

> For best results, make your image file 256 by 256, but only place content in the upper left 200 by 200 area. This area is then rendered at a 0.5x scale compared to the rest of the book in pixel size.

**Comment by agentwolf88** [comment]
Does not work. My picture is 256 by 256. Picture with 200 by 200 is the same problem.

**Comment by Hubry** [comment]
200x200 content in a 256x256 image, or just an 200x200 image? Read the docs again please
