### ISSUE TITLE
[1.16.5] Mixin issue in Dev

### ISSUE THREAD

**Issue by AzureDoom** [Vazkii/Patchouli#379]
Patchouli Version: 1.16.4-50
Forge version: 36.1.2

Hi I have since updated my dev to the latest Forge version and the official mappings, including adding
```
            properties 'mixin.env.disableRefMap': 'true'
            property 'mixin.env.refMapRemappingFile', "${project.projectDir}/build/createSrgToMcp/output.srg"
```
to my runs, however I am still receiving a mixin injection failure upon trying to enter a save. 

Here is my log:
https://gist.github.com/AzureDoom/94232eee2f72d6234d5a8cdf487d02d1

Here is my build.gradle:
https://gist.github.com/AzureDoom/da400927a9f6f5ef85fa37853234fd4a

**Comment by Hubry** [comment]
> `properties 'mixin.env.disableRefMap': 'true'`

The linked snippet:
> `property 'mixin.env.remapRefMap', 'true'`

I believe this is a typo on your side :V

**Comment by AzureDoom** [comment]
Ah that was it, thanks for the help!
