### ISSUE TITLE
.json does not have a valid category

### ISSUE THREAD

**Issue by bobdoby** [Vazkii/Patchouli#396]
Greetings

I started work on a modpack and I decided to use Patchouli as my guide book, but unfortunately I am not very well versed in java,
so please could someone assist this noob with this error

your help would be well appreciated.

![2021-05-07_14 21 50](https://user-images.githubusercontent.com/38683234/117448911-9f93dc00-af3f-11eb-94cb-8bbed9a34d8d.png)

**this is what is in test entry :**

{
    "name": "Test Entry",
    "icon": "minecraft:writable_book",
    "category": "bob_book:test_category",
    "pages": [
        {
            "type": "text",
            "text": "This is a test entry, but it should show up!"
        }
    ]
}

**and this is in test category :**

{
	"name": "Test Category",
	"description": "This is a test category for testing!",
	"icon": "minecraft:writable_book"
}

**Comment by williewillus** [comment]
please visit the #patchouli channel on Discord for support
