### ISSUE TITLE
Patchouli (patchouli) encountered an error during the sided_setup event phase 		com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by KetchupGaming** [Vazkii/Patchouli#408]
[crash-2021-06-17_17.22.33-fml.txt](https://github.com/Vazkii/Patchouli/files/6670002/crash-2021-06-17_17.22.33-fml.txt)

**Comment by Hubry** [comment]
Your `patchouli_data.json` from the instance root seems to be corrupted, delete it or try to make it somehow a valid json.
