### ISSUE TITLE
Book of Shadows Failing to Load

### ISSUE THREAD

**Issue by Inkquill256** [Vazkii/Patchouli#417]
When I try to use the Book of Shadows from the Bewitchment mod, I keep getting this error. Some of the pages work, but most of them are blank. 

![2021-06-23_21 10 29](https://user-images.githubusercontent.com/83196535/123187530-f5750280-d45f-11eb-9ffb-eb00abb0e13c.png)
![2021-06-23_21 10 44](https://user-images.githubusercontent.com/83196535/123187532-f5750280-d45f-11eb-8610-01816282eb6c.png)
![2021-06-23_21 10 15](https://user-images.githubusercontent.com/83196535/123187533-f60d9900-d45f-11eb-9d6d-94c51f55aa36.png)

**Comment by williewillus** [comment]
report it to bewitchment @MoriyaShiine
