### ISSUE TITLE
Crash When Using REI Search Bar

### ISSUE THREAD

**Issue by Brittank88** [Vazkii/Patchouli#418]
[Here's my crash report](https://gist.github.com/Brittank88/3d73349f84e86f3645bfbc14d1de9ed1). Let me know if you need any more info!

**Comment by williewillus** [comment]
is this in a patchouli book UI? does it happen without Patchouli?

**Comment by Brittank88** [comment]
It wasn't in the Patchouli book UI, no.

I tried removing Patchouli and now my game crashes on startup, and Patchouli still has a section in the crash log? This makes no sense - I have verified that Patchouli is not present in the mods folder.

**Comment by Brittank88** [comment]
Ah, I believe some other mod requires Patchouli to run. I'm new to Fabric modpack design and I would have expected it to be brought up as a dependency warning.

I'm not sure how to quickly figure out which mod here requires Patchouli.

**Comment by Brittank88** [comment]
I'm going to close this because I'm beginning to realise that this is actually probably unrelated to Patchouli and I have simply read the crash log wrong.

Re-reading it, I see that it tried to narrate something on the screen (likely from the REI GUI) and crashed as a result. Patchouli just always adds its own section to the crash log, but I thought this meant it was related somehow.
