### ISSUE TITLE
[1.16.5]Pressing "E" in patchouli book index search closes book

### ISSUE THREAD

**Issue by theboo** [Vazkii/Patchouli#419]
minecraft ver: 1.16.5
patchouli ver: 1.16.4-53
When searching in the index section of a patchouli book, you cannot currently search anything with the letter "e" as it kicks you out of the book gui.
Issue shown here with just ars nouveau and patchouli, but i also tested with a few other mods that use patchouli books including occultism, industrial foregoing and pneumaticraft: repressurized, all by themselves with just patchouli and their other dependencies.:
cant see much but i'm trying to type "hello"
https://streamable.com/16rs1k

**Comment by williewillus** [comment]
@LeoBeliik u brok it

**Comment by theboo** [comment]
Thanks a bunch!
