### ISSUE TITLE
Allow NBT support for ItemStack icons

### ISSUE THREAD

**Issue by ejektaflex** [Vazkii/Patchouli#51]
It would be nice to be able to use itemstack icons for items that have a different look depending on their NBT data. A good example of this would be bees from Forestry: Their looks change depending on their NBT data, but as of right now there's no way to set that. Same could be said of a Tinkers' Construct tool icon.

Edit: This could be useful for recipes that have an NBT-specific output as well.

**Comment by ejektaflex** [comment]
This feature actually does already exist, but isn't documented in the wiki. I found it via Nature's Aura, they do it in some of their book content. Closed.

**Comment by Vazkii** [comment]
It is most definitely documented:
https://github.com/Vazkii/Patchouli/wiki/ItemStack-String-Format

**Comment by netcore10** [comment]
This is outdated, i get an error with everything i try.

**Comment by Sv443** [comment]
> This is outdated, i get an error with everything i try.

I got it to work with the syntax `"namespace:item_name[namespace:component_name='value']"` (I'm on 1.21.1, using the relatively recent item components)  
The [new wiki doesn't list this syntax](https://vazkiimods.github.io/Patchouli/docs/patchouli-advanced/itemstack-format/#format), it says to use `namespace:item_name{nbt}`, which doesn't work.  
  
Example: if I wanted to show in the first guide book that there was a second one, I could make this entry:  
```json
{
    "name": "Second Guide Book",
    "icon": "patchouli:guide_book[patchouli:book='my_mod:guide_book_2']",
    "category": "my_mod:category",
    "pages": [
        {
            "type": "patchouli:spotlight",
            "item": "patchouli:guide_book[patchouli:book='my_mod:guide_book_2']",
            "link_recipe": true,
            "title": "Second Guide Book",
            "text": "The second edition of the guide book, containing less important information."
        }
    ]
}
```
