### ISSUE TITLE
Problem Or Feature Request If Its Not A Problem.

### ISSUE THREAD

**Issue by OtisGoodman** [Vazkii/Patchouli#56]
Is there a way to use items for things with damage.

For instance, let's say I want to make a damaged item an icon for an entry.
If it exists can someone give me an example 
else {
mod.add(this);
}

**Comment by Daomephsta** [comment]
https://github.com/Vazkii/Patchouli/wiki/ItemStack-String-Format

**Comment by OtisGoodman** [comment]
k thanks
