### ISSUE TITLE
Landing page categories have no overflow handling

### ISSUE THREAD

**Issue by primetoxinz** [Vazkii/Patchouli#61]
The book will continue to render categories past the bounds of the page
![](https://cloud.primetoxinz.com/s/GwyQF2zydJZycZj/preview)

To handle overflow I think it should make a new page

**Comment by Vazkii** [comment]
At that point you should look into nesting these categories, honestly.

**Comment by primetoxinz** [comment]
I am not actually using this many categories, I just posted this as I considered using that many and expected this is what would happen.
