### ISSUE TITLE
Issues with metadata

### ISSUE THREAD

**Issue by SynfulChaot** [Vazkii/Patchouli#68]
There appear to be several odd issues when trying to use items with metadata.

1. If you specify a block with metadata as a mapping in a multiblock, that block will not appear.
2. If you try to display the recipe of a block or item with metadata on a crafting recipe page, the page will appear blank

Version Affected: 1.0-10

**Comment by Vazkii** [comment]
Both of these are user error. For 1, you can't use metadata, you use blockstates. Check the multiblock wiki page. For 2, you don't use the item/block ID, you use the recipe ID.
