### ISSUE TITLE
[Feature Request] Add a book JSON key to allow you to start with the book in your inventory

### ISSUE THREAD

**Issue by SynfulChaot** [Vazkii/Patchouli#69]
Would it be possible to add a JSON key to allow pack makers like myself to create books that players can begin with in their inventory?  Something along the lines of `"starting_inventory": true`.

This would be a boon to pack makers that want to use Patchouli to create a guide to the pack without requiring the player to know how to craft the book.

**Comment by Vazkii** [comment]
This is out of scope for the mod. There's other mods that allow you to give players a starting inventory.
