### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by OtisGoodman** [Vazkii/Patchouli#73]
How do I create advancements which use the guide item?

**Comment by tterrag1098** [comment]
I believe creating custom advancements is outside the scope of this mod. Either make your own mod with advancements, or use a content-creation mod (I think ContentTweaker supports advancements?) to add them.

**Comment by OtisGoodman** [comment]
I am trying to make one where if you have the guide in your inv it triggers.

**Comment by OtisGoodman** [comment]
but I don't know how to make it so that it only triggers with my mods book.

**Comment by OtisGoodman** [comment]
also, how would I add a crafting recipe for my mods guide?

**Comment by Vazkii** [comment]
Updated the getting started page with info on this: https://github.com/Vazkii/Patchouli/wiki/Getting-Started#7-use-the-book-item

**Comment by OtisGoodman** [comment]
thanks m8
