### ISSUE TITLE
Multiblock Rendering Issue

### ISSUE THREAD

**Issue by LordPINE** [Vazkii/Patchouli#79]
When making a multiblock containing gaia pylons, everything except said pylons renders.
They show up in the multiblock visualization as mana pylons as well.

Relevant json:
https://pastebin.com/xQwQ4XnX

This happens on the latest version of Patchouli (1.0-12).

**Comment by tterrag1098** [comment]
In the case of a TESR failing to render there is only so much patchouli can do to simulate a world...this should be reported to the owner of the renderer (botania) to add better compatibility for rendering in a simulated world.
