### ISSUE TITLE
[Feature Request] Tinkers Alloying Recipe support

### ISSUE THREAD

**Issue by duhadventure** [Vazkii/Patchouli#80]
![image](https://user-images.githubusercontent.com/8278338/50027340-82969100-ffb1-11e8-9e81-1dc1151e274c.png)
The ability to display alloy recipes from Tinker's in the books. This is an example in my pack using Terrasteel, a custom melted dragon egg fluid, and Vibranium from Taiga to make a metal.

**Comment by Drullkus** [comment]
You can write your own custom Template Processor in the code to support this. I think Vazkii doesn’t have interest in supporting other mods natively, but he provided an API so mods can write it themselves.
