### ISSUE TITLE
Header component is incorrectly handling centered string

### ISSUE THREAD

**Issue by 3TUSK** [Vazkii/Patchouli#81]
### Synopsis
In a header component used by a custom template, the field `centered` has no effect regardless what value is set; it will always cause a left-aligned header to be rendered.

### Reproduction

1. Environment is Forge 14.23.5.2772 and Patchouli 1.0-11.55.
2. Use this minimal template, and set value for `header_text` in the actual entry json, and then load it in-game.

```json
{
  "components": [
    {
      "type": "header",
      "text": "#header_text",
      "centered": true,
      "x": 10,
      "y": 0
    }
  ]
}
```

3. Sample picture of an entry page using the said template

![image](https://user-images.githubusercontent.com/9113033/50040770-acc27000-fffe-11e8-8e17-1a88f14cc355.png)

### Analysis

https://github.com/Vazkii/Patchouli/blob/83c02b4c23a1f1f2cbf77acde96a57b238922261/src/main/java/vazkii/patchouli/client/book/template/component/ComponentHeader.java#L44-L46

Right now two branches of the if-else clause shown above effectively does the same thing. However, according to [documentation of header component](https://github.com/Vazkii/Patchouli/wiki/Template-Components#header-components):

> * centered (boolean)
> Defaults to true. Set to false to align the text to the left rather than center.

Therefore, the if-else clause should have been:

```java
 if(centered) 
 	page.parent.drawCenteredStringNoShadow(text, GuiBook.PAGE_WIDTH / 2, 0, color); 
 else page.fontRenderer.drawString(text, 0, 0, color); 
```

which is similar to:
https://github.com/Vazkii/Patchouli/blob/83c02b4c23a1f1f2cbf77acde96a57b238922261/src/main/java/vazkii/patchouli/client/book/page/PageText.java#L47-L48

### Final words

> dunno why this hasn't been noticed. Should be an easy fix; I can PR the fix if that's preferred.

**Comment by primetoxinz** [comment]
[Why does this centered property exist at all given that setting x to -1 does the same thing](
https://github.com/Vazkii/Patchouli/blob/83c02b4c23a1f1f2cbf77acde96a57b238922261/src/main/java/vazkii/patchouli/client/book/template/component/ComponentHeader.java#L32-L33)

**Comment by primetoxinz** [comment]
My suggestion for a change would to change the previously linked lines to this
```
if(x == -1 || centered)
    x = GuiBook.PAGE_WIDTH / 2;
```

**Comment by Vazkii** [comment]
This is intended behaviour @primetoxinz. You may want to center the header elsewhere other than the actual page center. This is properly documented in the Header Components section of the wiki.
