### ISSUE TITLE
[Suggestion/Potential Issue] Namespaces for Extended Books

### ISSUE THREAD

**Issue by Quarris** [Vazkii/Patchouli#82]
Are namespaces allowed in extended books? I'm trying to add a namespace for my mod but the entry shown in the second picture still stays locked. I've tried looking for typos and I seriously hope I haven't made any. Is there something I'm doing wrong?
![image](https://user-images.githubusercontent.com/6171764/50222728-0628f700-0391-11e9-8c0d-0f63195e0fa0.png)

![image](https://user-images.githubusercontent.com/6171764/50222716-ff9a7f80-0390-11e9-8020-be2e3e330f8c.png)

P.S. I have done it with an different advancement not in my namespace and it unlocks fine.

**Comment by Vazkii** [comment]
They're not, but they should be. Good catch.
