### ISSUE TITLE
Recipes showing as shapeless even though they are not

### ISSUE THREAD

**Issue by neothiamin** [Vazkii/Patchouli#83]
I've added some recipes to some pages in my book, and of the three recipes, all are showing as shapeless even though they are shaped, and one is showing incorrectly. As a disclaimer, these items are staged using GameStages so that may be messing with the recipe registration.

![2018-12-24_11 36 08](https://user-images.githubusercontent.com/8920936/50403935-cab37180-0770-11e9-92aa-88005c914bbb.png)
![2018-12-24_11 36 11](https://user-images.githubusercontent.com/8920936/50403936-cab37180-0770-11e9-9207-d4f8c59f71c5.png)
![2018-12-24_11 36 16](https://user-images.githubusercontent.com/8920936/50403937-cab37180-0770-11e9-8bb0-af042fd7efe9.png)
![2018-12-24_11 36 18](https://user-images.githubusercontent.com/8920936/50403934-cab37180-0770-11e9-96c5-fd2db4c6dffe.png)

As you can see, the recipe for the Refractory Casings and Melting Crucible are showing as shapeless, but with the correct, shaped recipe, and the Burner Heater is showing as shapeless with an incorrect recipes. The recipes are unchanged via CraftTweaker etc., and the recipe IDs are correct.

The JSON for the entry can be found [here](https://gist.github.com/neothiamin/7efe62456ce242a50d30fb349d59bce0).

**Comment by Vazkii** [comment]
Nevermind, I looked through RecipeStages' code. @jaredlll08 these recipes don't implement IShapedRecipe if they're shaped.
https://github.com/jaredlll08/RecipeStages/blob/master/src/main/java/com/blamejared/recipestages/recipes/RecipeStage.java

**Comment by neothiamin** [comment]
Ah, alright, that's a shame, but I'll find a workaround. Thank you!
