### ISSUE TITLE
Category and entry text doesn't accept localization keys like book.json text does

### ISSUE THREAD

**Issue by Yuudaari** [Vazkii/Patchouli#9]
Category names, category descriptions, entry names, and entry text do not accept localization keys (IE, they don't translate them). I assumed this would be a thing since I was able to use localization keys for both the `landing_text` and `subtitle` of my book. I like having all of my english in one place.

**Comment by Vazkii** [comment]
I'm going to move this to "intended behaviour".

**Comment by Yuudaari** [comment]
@Vazkii Oh, that's too bad. I should have mentioned another reason I wanted this — I'm probably going to make two separate guidebooks for my mod and change which one is used via a config; I can reuse some of the english if this is a thing, but otherwise I have to clone all the text.

Isn't this also like, way worse for translators, as well? Having to edit & pass around more files than just a single lang file?
