### ISSUE TITLE
Feature Request: API method to open book at a specific entry ID

### ISSUE THREAD

**Issue by desht** [Vazkii/Patchouli#94]
As the subject says: it would be nice to be able to do something like
```java
// server version
PatchouliAPI.instance.openBookGUI(EntityPlayerMP player, bookResourceLocation, "category_id/entry_id");
// client version
PatchouliAPI.instance.openBookGUI(bookResourceLocation, "category_id/entry_id");
```

My particular use-case is the [PneumaticCraft programmer](https://i.ytimg.com/vi/35RXPwU1Bzw/maxresdefault.jpg), where I'd like to be able to hover over one of the programming widgets and press a hotkey to open the documentation for that widget (this is possible right now with IGWmod, but I want to support Patchouli too!)

As a bonus feature, it would also be useful to have some way to prevent the user leaving that entry, in the case where you might want to allow opening a specific entry, but not allow general book browsing without an actual book in your inventory.

**Comment by Davoleo** [comment]
I agree, a method like this would be really useful to link documentation to buttons or hotkeys!

**Comment by williewillus** [comment]
this exists in 1.15 now
